### ISSUE TITLE
429 Client Error when trying to migrate editions

### ISSUE THREAD

**Issue by zorae** [internetarchive/openlibrary#10039]
### Problem

I'm currently unable to use the _migrate editions_ script on Google Colab, which used to work flawlessly. When trying to run its works=… code block, I get an error that I interpret as being caused by an issue with the OL servers.

```
ERROR:backoff:Giving up get_ol_response(...) after 1 tries (requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://openlibrary.org/authors/OL2890A.json)
ERROR:openlibrary:Error retrieving OpenLibrary response: {'target': <function OpenLibrary.get_ol_response at 0x78772d57b0a0>, 'args': (<olclient.openlibrary.OpenLibrary object at 0x78772dd137c0>, '/authors/OL2890A.json'), 'kwargs': {}, 'tries': 1, 'elapsed': 1.1e-05, 'exception': HTTPError('429 Client Error: Too Many Requests for url: https://openlibrary.org/authors/OL2890A.json')}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/olclient/openlibrary.py", line 150, in get_ol_response
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://openlibrary.org/authors/OL2890A.json
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-4-4478068a6bae> in <cell line: 5>()
      4 works = [ol.Work.get(olid) for olid in dupes.split(',')]
      5 for work in works:
----> 6   editions = work.editions
      7   print(f"{work.olid}: {len(editions)} edition(s)")

7 frames
/usr/local/lib/python3.10/dist-packages/requests/models.py in raise_for_status(self)
   1019 
   1020         if http_error_msg:
-> 1021             raise HTTPError(http_error_msg, response=self)
   1022 
   1023     def close(self):

HTTPError: 429 Client Error: Too Many Requests for url: https://openlibrary.org/authors/OL2890A.json
```

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by cdrini** [comment]
We have new protections to help prevent spam; you might have to add some `sleep` between the calls so that it's not firing too many requests all at once. Do you have the link to the google colab which you ran?

**Comment by zorae** [comment]
@cdrini https://colab.research.google.com/drive/1c25MdxcaOTbNq6vu1A-ORJB6X5daMe79?usp=sharing

**Comment by cdrini** [comment]
Ah this is pretty deep in the open library client to fix properly... Could you try adding a `sleep` to the end of the for loop? I.e. change that cell to this:

```py
import time
dupes = 'OL16290253W'  #@param { type: "string" }
into_olid = 'OL262496W'  #@param { type: "string" }

works = [ol.Work.get(olid) for olid in dupes.split(',')]
for work in works:
  editions = work.editions
  print(f"{work.olid}: {len(editions)} edition(s)")
  time.sleep(5)
```

Also, how many works were you editing? E.g. what was the `dupes` field set to?

**Comment by zorae** [comment]
This appears to be resolved
