### ISSUE TITLE
bundlesize fails on `make test` in docker image 

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#1240]
The css `bundlesize` tests fail inside the dev docker container.

on `make test`:

```
sh: 1: bundlesize: not found

npm ERR! Linux 4.4.0-135-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "check-bundles"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! openlibrary@1.0.0 check-bundles: `npm run build-assets && bundlesize`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the openlibrary@1.0.0 check-bundles script 'npm run build-assets && bundlesize'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openlibrary package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-assets && bundlesize
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openlibrary
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openlibrary
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /openlibrary/npm-debug.log
npm ERR! Test failed.  See above for more details.
Makefile:98: recipe for target 'test' failed
make: *** [test] Error 1
```

Installing bundlesize globally with 
`npm install bundlesize -g`

still fails, but with a different error:
```
make[1]: Leaving directory '/openlibrary'
/openlibrary/node_modules/bundlesize/index.js:3
const { inspect } = require('util')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

This is what I was seeing in 1136 (description)

The docker Xenial image has versions `(current: {"node":"4.2.6","npm":"3.5.2"})`

**Comment by hornc** [comment]
@jdlrobson I was really battling npm on this one -- are you able to comment on the requirements for `bundlesize`?  I'm guessing at this point that it needs a newer version of npm or node to run?

**Comment by jdlrobson** [comment]
Thanks for the comprehensive report!

We'll need to use at least node 6 to support { inspect } = require('util') syntax.
Ideally we should be using node 8.
4.2.6 is very old.

**Comment by jdlrobson** [comment]
Did you work this out @hornc ?

**Comment by tfmorris** [comment]
This breaks the build in Vagrant environments too. 

What is our minimum required version of node.js? What version is used in the production environment?

We should configure our Jenkins CI jobs with whatever we use in other environments so that we don't break things without knowing about it. Obviously we can't just assume arbitrary versions since this has to be coordinated across multiple environments.

**Comment by tfmorris** [comment]
I've started to repair both dev environments on this branch:
https://github.com/tfmorris/openlibrary/tree/1240-nodejs-versions
but ran out of time before finishing testing.

A related issue that needs to be fixed is moving /openlibrary/node_modules to a place that isn't shared because of the potential for cross architecture contamination (ie conflicting binaries for different O/S or CPU in Docker/Vagrant vs host)

**Comment by mekarpeles** [comment]
```
$ node -v && npm -v
v0.10.25
1.3.10
```

**Comment by jdlrobson** [comment]
Check nodejs -v as on some ubuntu builds node is something else and that version seems suspiciously  old...

**Comment by mekarpeles** [comment]
```
$ nodejs -v
v0.10.25
```

**Comment by jdlrobson** [comment]
Wowser! So old! We can bump that up to at least 6, right...?!?

**Comment by tfmorris** [comment]
Well, that was painful! The better part of a month later and two wasted development sessions I think I've got both the Docker and Vagrant development environments repaired.

Doesn't really seem like I should have been the one to have to pay the penalty for the broken dev environment, but hopefully it's repaired now if someone wants to review the PR.

p.s. I did **not** change the Docker environment's use of Xenial, which I believe is at odds with both our production environment and our CI infrastructure which I think use Trusty

**Comment by hornc** [comment]
The Xenial vs Trusty probably needs a bigger discussion, and its own issue. I think you raise a valid point, that there is a mismatch between dev and prod versions. I think there is value in the Xenial dev images since they show the upgrade path is possible and functions, but we should have a corresponding Trusty dev version too.
