### ISSUE TITLE
Error calculating book pages count in Author view

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1357]
Error calculating book pages count in `openlibrary/templates/type/author/view.html`
```
Traceback (most recent call last):
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/template.py", line 146, in saferender
    result = t(*a, **kw)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/web/template.py", line 868, in __call__
    return BaseTemplate.__call__(self, *a, **kw)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/web/template.py", line 781, in __call__
    return self._join_output(out)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/web/template.py", line 787, in _join_output
    for name, value in out:
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/templates/type/author/view.html", line 246, in __template__
    $ pages = (books.num_found / 100) + 1
TypeError: unsupported operand type(s) for /: 'instance' and 'int'
```

**Comment by shreyansh23** [comment]
@mekarpeles 
Is this issue still open?

**Comment by LeadSongDog** [comment]
@shreyansh23 Is books.num_found of type int when there are no books found? It looks as if that might be the issue.

**Comment by mekarpeles** [comment]
I think we should close the issue given no example URL is provided, which is my fault as the issue creator. Thanks all!

Will reopen with an example if I encounter this again
