### ISSUE TITLE
Bug in  copydocs.py

### ISSUE THREAD

**Issue by Hardcore-fs** [internetarchive/openlibrary#147]
/home/openlibrary/env/bin/python /home/openlibrary/scripts/copydocs.py /books/OL6041261M --recursive

There is a problem with  'OL6041261M'

2012-05-24 09:06:10 [infobase.cache] [DEBUG] MemcachedDict.update: ['/type/type', '/people/admin', '/type/toc_item', '/type/text', '/type/property', '/type/edition', '/type/work', '/type/scan_record', '/type/collection', '/type/volume', '/type/string', '/type/language', '/type/boolean', '/type/int', '/type/author']
127.0.0.1:36479 - - [24/May/2012 09:06:10] "HTTP/1.1 POST /api/save_many" - 400 Bad Request
Traceback (most recent call last):
  File "/home/openlibrary/scripts/copydocs.py", line 247, in <module>
    main()
  File "/home/openlibrary/scripts/copydocs.py", line 244, in main
    copy(src, dest, keys, comment=options.comment, recursive=options.recursive)
  File "/home/openlibrary/scripts/copydocs.py", line 175, in copy
    print dest.save_many(docs, comment=comment)
  File "/home/openlibrary/openlibrary/api.py", line 140, in save_many
    return self._call_write('save_many', query, comment, action)
  File "/home/openlibrary/openlibrary/api.py", line 136, in _call_write
    response = self._request('/api/' + name, method="POST", data=simplejson.dumps(query), headers=headers)
  File "/home/openlibrary/openlibrary/api.py", line 50, in _request
    raise OLError(e)
openlibrary.api.OLError: Bad Request: {"message": "expected /type/toc_item, found /type/text", "at": {"property": "table_of_contents", "key": "/books/OL6041261M"}, "value": "Brandenburgische Nacht.", "error": "bad_data"}

**Comment by LeadSongDog** [comment]
Why is it that 
 https://openlibrary.org/search/authors?q=Fritz+Helke
shows exactly one author who has "8 books about..."
But 
 https://openlibrary.org/authors/OL154735A/Fritz_Helke 
shows 6 works of one edition each?

**Comment by jessamynwest** [comment]
When I click that top link I show six books. Maybe it's something that's been fixed? I know there has been work on the index today.

**Comment by LeadSongDog** [comment]
Yes that has since somehow been fixed. A similar discrepancy:
 https://openlibrary.org/search/authors?q=Homer+%28poet%29 shows "39 books"
 https://openlibrary.org/authors/OL6848355A/Homer_(poet)  shows "40 works" one with 623 editions.

**Comment by LeadSongDog** [comment]
Well, since then something has changed. The same queries now report "39 books" and "1499 works" respectively. Of those 1499 works, only around 270 have any editions.

**Comment by jdlrobson** [comment]
```
copydocs.py /books/OL6041261M --recursive
```
is working for me.
Is this bug from 2012 fixed?

**Comment by mekarpeles** [comment]
closing for now
