### ISSUE TITLE
Docker: Cannot make HTTP requests (connection refused)

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1587]
```
docker-compose exec web bash
cd scripts
root@a8bc71d4e028:/openlibrary/scripts# ./copydocs.py "/books/OL11627541M"
Traceback (most recent call last):
  File "./copydocs.py", line 248, in <module>
    main()
  File "./copydocs.py", line 235, in main
    dest.login("admin", "admin123")
  File "/openlibrary/openlibrary/api.py", line 97, in login
    response = self._request('/account/login', method='POST', data=data, headers=headers)
  File "/openlibrary/openlibrary/api.py", line 53, in _request
    return urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
```
I'm guessing we need to give the Docker container access to the web.
This is essential for importing content into a local instance.

**Comment by jdlrobson** [comment]
Please help me with this! :(

**Comment by jdlrobson** [comment]
Okay I got this working... but I needed a few parameters
```
./copydocs.py "/works/OL3086095W/" --src http://openlibrary.org --dest http://localhost --recursive
```
I've updated this here:
https://github.com/internetarchive/openlibrary/wiki/Getting-Started#importing-test-data

Do we need to change the defaults of this script or is that documentation change enough?

I'm worrying this might trip somebody else up...

**Comment by hornc** [comment]
sorry @jdlrobson I only found this now, PR raised to fix the root cause of this problem and set some sensible defaults.

**Comment by jdlrobson** [comment]
hurray! confirmed working! thank you for fixing!
