### ISSUE TITLE
[infobase.client] [ERROR] Unable to connect to infobase server

### ISSUE THREAD

**Issue by tracefoundation** [internetarchive/openlibrary#210]
I'm getting this error from the "make bootstrap" from the master branch, am i missing some configuration? 

here the error stack:

```
Wed Feb 26 11:56:09 2014 DEBUG  openlibrary database is already present

Wed Feb 26 11:56:09 2014 DEBUG  Executing '/home/alex/openlibrary/env/bin/python ./scripts/openlibrary-server conf/openlibrary.yml install'

2014-02-26 11:56:09 [openlibrary] [INFO] Application init
2014-02-26 11:56:09 [openlibrary] [INFO] loading plugin openlibrary
2014-02-26 11:56:09 [openlibrary] [INFO] loading plugin search
2014-02-26 11:56:09 [openlibrary] [INFO] loading plugin worksearch
2014-02-26 11:56:09 [openlibrary] [INFO] loading plugin inside
2014-02-26 11:56:09 [openlibrary] [INFO] loading plugin books
2014-02-26 11:56:09 [openlibrary] [INFO] loading plugin admin
2014-02-26 11:56:09 [openlibrary] [INFO] loading plugin upstream
2014-02-26 11:56:09 [openlibrary] [INFO] loading plugin importapi
2014-02-26 11:56:09 [openlibrary] [INFO] loading plugin recaptcha
2014-02-26 11:56:09 [openlibrary] [INFO] loading complete.
2014-02-26 11:56:09 [infobase] [INFO] loading plugin openlibrary.olbase
ERR: SELECT * FROM thing LIMIT 1
2014-02-26 11:56:09 [infobase.ol] [INFO] logging initialized
2014-02-26 11:56:09 [infobase.ol] [DEBUG] debug
2014-02-26 11:56:09 [openlibrary.olbase] [INFO] setting up infobase events for Open Library
ERR: SELECT * FROM thing LIMIT 1
ERR: SELECT * FROM thing LIMIT 1
ERR: SELECT * FROM thing LIMIT 1
2014-02-26 11:56:09 [infobase.client] [ERROR] Unable to connect to infobase server
Traceback (most recent call last):
  File "/home/alex/openlibrary/infogami/infobase/client.py", line 153, in request
    conn.request(method, path, data, headers=headers)
  File "/usr/lib/python2.7/httplib.py", line 958, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 992, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 757, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "./scripts/openlibrary-server", line 132, in <module>
    main()
  File "./scripts/openlibrary-server", line 129, in main
    start_server()
  File "./scripts/openlibrary-server", line 45, in start_server
    infogami.run(args)
  File "/home/alex/openlibrary/infogami/__init__.py", line 148, in run
    run_action(args[0], args[1:])
  File "/home/alex/openlibrary/infogami/__init__.py", line 135, in run_action
    a(*args)
  File "/home/alex/openlibrary/infogami/__init__.py", line 92, in install
    web.ctx.site.create()
  File "/home/alex/openlibrary/infogami/infobase/client.py", line 303, in create
    self._request(path="", method="PUT")
  File "/home/alex/openlibrary/infogami/infobase/client.py", line 216, in _request
    out = self._conn.request(self.name, path, method, data)
  File "/home/alex/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 59, in request
    return self.conn.request(sitename, path, method, data)
  File "/home/alex/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 59, in request
    return self.conn.request(sitename, path, method, data)
  File "/home/alex/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 604, in request
    return self.writer.request(sitename, path, method, data=data)
  File "/home/alex/openlibrary/infogami/infobase/client.py", line 159, in request
    raise ClientException("503 Service Unavailable", "Unable to connect to infobase server")
infogami.infobase.client.ClientException: Unable to connect to infobase server
Traceback (most recent call last):
  File "scripts/setup_dev_instance.py", line 450, in <module>
    setup_ol().run()
  File "scripts/setup_dev_instance.py", line 269, in run
    system(INTERP + " ./scripts/openlibrary-server conf/openlibrary.yml install")
  File "scripts/setup_dev_instance.py", line 119, in system
    raise Exception("%r failed with exit code %d" % (cmd, ret))
Exception: '/home/alex/openlibrary/env/bin/python ./scripts/openlibrary-server conf/openlibrary.yml install' failed with exit code 256
make: *** [setup_ol] Error 1
```

**Comment by hornc** [comment]
FWIW, I have been able to recently (Sep 2016) set up a Vagrant dev environment on a new Ubuntu machine. I have not had issues with any git sub-modules.

**Comment by hornc** [comment]
closing as these are old reports. Current vagrant dev environment is being used by multiple developers. If there are still any problems with getting set up we will address them in new reports.
