### ISSUE TITLE
Open Library / latest Infogami integration issue

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2903]
Running OL under the standard Python 2.7 but updating `vendor/infogami`  to the latest commit https://github.com/internetarchive/infogami @ b3dfccd577c42d79cec62d9c9002fd37fc869cc3  
produces the following error trace in local docker when a work page is loaded:

URL: http://localhost:8080/works/OL61982W/Odyssey

```
web_1        | error saved to /var/log/openlibrary/ol-errors/2020-01-22/052718724258.html
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/infogami/utils/template.py", line 143, in saferender
web_1        |     result = t(*a, **kw)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/web/template.py", line 881, in __call__
web_1        |     return BaseTemplate.__call__(self, *a, **kw)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/web/template.py", line 808, in __call__
web_1        |     return self.t(*a, **kw)
web_1        |   File "/openlibrary/openlibrary/templates/viewpage.html", line 27, in __template__
web_1        |     $var title: $:view.title
web_1        |   File "/openlibrary/openlibrary/core/models.py", line 127, in prefetch
web_1        |     preview = self.get_history_preview()
web_1        |   File "/openlibrary/openlibrary/core/cache.py", line 535, in g
web_1        |     cache[f.__name__] = f(self)
web_1        |   File "/openlibrary/openlibrary/core/models.py", line 72, in get_history_preview
web_1        |     history = self._get_history_preview()
web_1        |   File "/openlibrary/openlibrary/core/cache.py", line 449, in func
web_1        |     value = f(*args, **kwargs)
web_1        |   File "/openlibrary/openlibrary/core/models.py", line 96, in _get_history_preview
web_1        |     h['recent'] = self._get_versions(limit=5)
web_1        |   File "/openlibrary/openlibrary/core/models.py", line 106, in _get_versions
web_1        |     versions = self._site.versions(q)
web_1        |   File "/openlibrary/infogami/infobase/client.py", line 367, in versions
web_1        |     versions =  self._request('/versions', 'GET', {'query': query})
web_1        |   File "/openlibrary/infogami/infobase/client.py", line 220, in _request
web_1        |     out = self._conn.request(self.name, path, method, data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 38, in request
web_1        |     return self.versions(sitename, data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 222, in versions
web_1        |     return ConnectionMiddleware.versions(self, sitename, data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 74, in versions
web_1        |     return self.conn.request(sitename, '/versions', 'GET', data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 38, in request
web_1        |     return self.versions(sitename, data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 74, in versions
web_1        |     return self.conn.request(sitename, '/versions', 'GET', data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 38, in request
web_1        |     return self.versions(sitename, data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 74, in versions
web_1        |     return self.conn.request(sitename, '/versions', 'GET', data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 535, in request
web_1        |     return self.reader.request(sitename, path, method, data=data)
web_1        |   File "/openlibrary/infogami/infobase/client.py", line 105, in request
web_1        |     out = server.request(path, method, data)
web_1        |   File "/openlibrary/infogami/infobase/server.py", line 604, in request
web_1        |     return tocall(*args)
web_1        |   File "/openlibrary/infogami/infobase/server.py", line 100, in g
web_1        |     result = simplejson.dumps(d)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 382, in dumps
web_1        |     return _default_encoder.encode(obj)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 296, in encode
web_1        |     chunks = self.iterencode(o, _one_shot=True)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 378, in iterencode
web_1        |     return _iterencode(o, 0)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 273, in default
web_1        |     o.__class__.__name__)
web_1        | TypeError: Object of type datetime is not JSON serializable

```

from the HTML error log:

```
  </li>
<li class="frame">
<code>/openlibrary/infogami/infobase/server.py</code> in <code>g</code>
<div class="context" id="c140110232483456">
<ol start="92" class="pre-context" id="pre140110232483456">
<li onclick="toggle('pre140110232483456', 'post140110232483456')">                raise common.InfobaseException(message=str(e))</li>
<li onclick="toggle('pre140110232483456', 'post140110232483456')">            else:</li>
<li onclick="toggle('pre140110232483456', 'post140110232483456')">                process_exception(e)</li>
<li onclick="toggle('pre140110232483456', 'post140110232483456')"></li>
<li onclick="toggle('pre140110232483456', 'post140110232483456')">        if isinstance(d, JSON):</li>
<li onclick="toggle('pre140110232483456', 'post140110232483456')">            result = d.json</li>
<li onclick="toggle('pre140110232483456', 'post140110232483456')">        else:</li>
</ol>
<ol start="99" class="context-line"><li onclick="toggle('pre140110232483456', 'post140110232483456')">            result = simplejson.dumps(d) <span>...</span></li></ol>
<ol start='100' class="post-context" id="post140110232483456">
<li onclick="toggle('pre140110232483456', 'post140110232483456')"></li>
<li onclick="toggle('pre140110232483456', 'post140110232483456')">        t_end = time.time()</li>
<li onclick="toggle('pre140110232483456', 'post140110232483456')">        totaltime = t_end - t_start</li>
<li onclick="toggle('pre140110232483456', 'post140110232483456')">        querytime = web.ctx.pop(&#39;querytime&#39;, 0.0)</li>
<li onclick="toggle('pre140110232483456', 'post140110232483456')">        queries = web.ctx.pop(&#39;queries&#39;, 0)</li>
<li onclick="toggle('pre140110232483456', 'post140110232483456')"></li>
</ol>
```

**Comment by hornc** [comment]
Unsure if it is related, but it demonstrates there is something different about the classes being returned, viewing the json of this work shows the following for `links`:

http://localhost:8080/works/OL61982W.json

```
links: [
{
url: "<bound method Thing.url of <Thing: {'url': "<bound method Thing.url of <Thing: {'url': 'http://en.wikipedia.org/wiki/Odyssey', 'type': <Thing: u'/type/link'>, 'title': 'Wikipedia entry'}>>", 'type': <Thing: u'/type/link'>, 'title': 'Wikipedia entry'}>>",
type: {
key: "/type/link"
},
title: "Wikipedia entry"
}
],```

`url` is a Python method rather than a string.

**Comment by hornc** [comment]
https://github.com/internetarchive/infogami/blob/b3dfccd577c42d79cec62d9c9002fd37fc869cc3/infogami/infobase/server.py#L97-L100
is where the error is occurring, `d` is
```
d | [<Storage {'comment': None, 'created': datetime.datetime(2013, 3, 28, 7, 50, 48, 835814), 'ip': '127.0.0.1', 'author': u'/people/admin', 'bot': False, 'changes': u'[{"key": "/works/OL16226033W", "revision": 1}, {"key": "/works/OL15547698W", "revision": 1}, {"key": "/works/OL15673999W", "revision": 1}, {"key": "/works/OL53924W", "revision": 1}, {"key": "/works/OL5702375W", "revision": 1}, {"key": "/works/OL192489W", "revision": 1}, {"key": "/works/OL6037022W", "revision": 1}, {"key": "/works/OL15692545W", "revision": 1}, {"key": "/works/OL15437498W", "revision": 1}, {"key": "/works/OL8193488W", "revision": 1}, {"key": "/works/OL54120W", "revision": 1}, {"key": "/works/OL73243W", "revision": 1}, {"key": "/works/OL16075717W", "revision": 1}, {"key": "/works/OL1898308W", "revision": 1}, {"key": "/works/OL61982W", "revision": 1}, {"key": "/works/OL15298516W", "revision": 1}, {"key": "/works/OL20600W", "revision": 1}, {"key": "/works/OL45310W", "revision": 1}, {"key": "/works/OL15706726W", "revision": 1}, {"key": "/works/OL15400392W", "revision": 1}, {"key": "/works/OL13101191W", "revision": 1}, {"key": "/works/OL151880W", "revision": 1}, {"key": "/works/OL118420W", "revision": 1}, {"key": "/works/OL5688746W", "revision": 1}]', 'key': u'/works/OL53924W', 'action': u'bulk_update', 'author_id': 24, 'data': u'{}', 'id': 42, 'revision': 1}>]
-- | --
```

**Comment by tfmorris** [comment]
This sounds like an infogami bug with the current HEAD. It should be reported here https://github.com/internetarchive/infogami/issues

When it's fixed upstream, we can retest.

Is there a failing test associated with this? If not, can we write one? That would allow us to both use `git bisect` to narrow commit that introduced the problem as well as confirm that it gets fixed correctly (and doesn't regress in the future).

**Comment by tfmorris** [comment]
p.s. guessing from the two examples, it could be something as simple as a missing `str()` wrapper on a return value someplace.

**Comment by cclauss** [comment]
How to overcome “datetime.datetime not JSON serializable”? 

https://stackoverflow.com/questions/11875770/how-to-overcome-datetime-datetime-not-json-serializable/36142844#36142844
