### ISSUE TITLE
Docker image build fails

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2910]
Building the `olweb` image no longer works and which blocks all development because it needs to be rebuilt to include the new `deprecated` dependency.

### Evidence / Screenshot (if possible)

```
Collecting zipp>=0.5 (from importlib-metadata>=0.12; python_version < "3.8"->pytest==4.6.6->-r requirements_test.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/ee/f7/6c3ca4764a8025da9422825c2bc367fdc8dd115ebb52e4ef057f234938c4/zipp-2.0.0.tar.gz
  Running setup.py (path:/tmp/pip-build-j64QQ0/zipp/setup.py) egg_info for package zipp produced metadata for project name unknown. Fix your #egg=zipp fragments.

```
This is related to: https://github.com/jaraco/zipp/issues/14

### Proposal & Constraints

I've confirmed that updating to pip=9 will fix the problem. (The version that we're using from xenial is 8 and the current version is 20).

I'll generate a PR with the fix.

### Stakeholders
@hornc @cdrini @mekarpeles

**Comment by cdrini** [comment]
I didn't observe this when I ran `docker-compose build web` on my machine, but I think updating pip is good regardless, so :+1:

**Comment by hornc** [comment]
Mentioned in another comment (possibly not gothub) that zipp is a dependency of mockcache , which only gets used if there is no memcache available: https://github.com/internetarchive/openlibrary/search?utf8=✓&q=mockcache&type=

Not sure the value of zipp, but updating pip is a good idea.

Suggestion (optional): there is a suppress version warnings flag set on pip in the Dockerfiles that can probably be removed with this change.

**Comment by cdrini** [comment]
This is odd, I _am_ getting the zipp error when I try to run pytest in docker; why is zipp suddenly necessary?

```
root@372d06d36cd8:/openlibrary# pytest openlibrary/tests/accounts/test_models.py
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 7, in <module>
    from pytest import main
  File "/usr/local/lib/python2.7/dist-packages/pytest.py", line 8, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/local/lib/python2.7/dist-packages/_pytest/assertion/__init__.py", line 13, in <module>
    from _pytest.assertion import rewrite
  File "/usr/local/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py", line 24, in <module>
    from _pytest.assertion import util
  File "/usr/local/lib/python2.7/dist-packages/_pytest/assertion/util.py", line 11, in <module>
    import _pytest._code
  File "/usr/local/lib/python2.7/dist-packages/_pytest/_code/__init__.py", line 7, in <module>
    from .code import Code  # noqa
  File "/usr/local/lib/python2.7/dist-packages/_pytest/_code/code.py", line 15, in <module>
    import pluggy
  File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 11, in <module>
    import importlib_metadata
  File "/usr/local/lib/python2.7/dist-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
ImportError: No module named zipp
```

**Comment by cdrini** [comment]
And the only way I can install `zipp` is to update pip first, because otherwise I get this error:

```
root@372d06d36cd8:/openlibrary# pip install zipp
Collecting zipp
  Downloading https://files.pythonhosted.org/packages/11/b5/89f3ab6d45b2709863761bab58c574b2344ef215749abb5407818c21c9ca/zipp-2.1.0.tar.gz
  Running setup.py (path:/tmp/pip-build-6PK3Ca/zipp/setup.py) egg_info for package zipp produced metadata for project name unknown. Fix your #egg=zipp fragments.
  Requirement already satisfied (use --upgrade to upgrade): unknown from https://files.pythonhosted.org/packages/11/b5/89f3ab6d45b2709863761bab58c574b2344ef215749abb5407818c21c9ca/zipp-2.1.0.tar.gz#sha256=feae2f18633c32fc71f2de629bfb3bd3c9325cd4419642b1f1da42ee488d9b98 in /usr/local/lib/python2.7/dist-packages
Building wheels for collected packages: unknown, unknown
  Running setup.py bdist_wheel for unknown ... done
  Stored in directory: /root/.cache/pip/wheels/88/43/56/4c905e8a6e030619e7a8efb70528d51ecb188a07fa86cc78a4
  Running setup.py bdist_wheel for unknown ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6PK3Ca/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpxSUmMApip-wheel- --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  IOError: [Errno 2] No such file or directory: '/tmp/pip-build-6PK3Ca/unknown/setup.py'

  ----------------------------------------
  Failed building wheel for unknown
  Running setup.py clean for unknown
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6PK3Ca/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  IOError: [Errno 2] No such file or directory: '/tmp/pip-build-6PK3Ca/unknown/setup.py'

  ----------------------------------------
  Failed cleaning build dir for unknown
Successfully built unknown
Failed to build unknown
You are using pip version 8.1.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by cdrini** [comment]
So for anyone getting this error, the work around until a proper fix is implemented is to run inside docker:

```sh
pip install --upgrade pip
pip install zipp
```

**Comment by tfmorris** [comment]
I'm baffled that it's considered odd when I reported exactly this error a week ago and generated a PR to fix it. The odd part from my point of view is that my initial report wasn't believed.

Why not review and merge the PR instead of proposing workarounds? It includes the change you requested.
