### ISSUE TITLE
i18n strings yml error messages in logs on startup

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#3140]
When starting up the Docker image locally, early on in the log trace I see:

```
web_1        | 2020-03-06 04:09:09,214 INFO loading config from conf/openlibrary.yml
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
web_1        |     data = read_strings(p)
web_1        |   File "/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
web_1        |     execfile(path, env)
web_1        |   File "/openlibrary/openlibrary/i18n/it/strings.it.yml", line 3
web_1        |     revision: 21
web_1        |             ^
web_1        | SyntaxError: invalid syntax
web_1        | failed to load strings from /openlibrary/openlibrary/i18n/it/strings.it.yml
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
web_1        |     data = read_strings(p)
web_1        |   File "/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
web_1        |     execfile(path, env)
web_1        |   File "/openlibrary/openlibrary/i18n/mr/strings.mr.yml", line 2
web_1        | SyntaxError: Non-ASCII character '\xe0' in file /openlibrary/openlibrary/i18n/mr/strings.mr.yml on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
web_1        | failed to load strings from /openlibrary/openlibrary/i18n/mr/strings.mr.yml
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
web_1        |     data = read_strings(p)
web_1        |   File "/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
web_1        |     execfile(path, env)
web_1        |   File "/openlibrary/openlibrary/i18n/hi/strings.hi.yml", line 3
web_1        | SyntaxError: Non-ASCII character '\xe0' in file /openlibrary/openlibrary/i18n/hi/strings.hi.yml on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
web_1        | failed to load strings from /openlibrary/openlibrary/i18n/hi/strings.hi.yml
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
web_1        |     data = read_strings(p)
web_1        |   File "/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
web_1        |     execfile(path, env)
web_1        |   File "/openlibrary/openlibrary/i18n/nl/strings.nl.yml", line 3
web_1        |     about_us: Over ons
web_1        |             ^
web_1        | SyntaxError: invalid syntax
web_1        | failed to load strings from /openlibrary/openlibrary/i18n/nl/strings.nl.yml
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
web_1        |     data = read_strings(p)
web_1        |   File "/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
web_1        |     execfile(path, env)
web_1        |   File "/openlibrary/openlibrary/i18n/kn/strings.kn.yml", line 2
web_1        | SyntaxError: Non-ASCII character '\xe0' in file /openlibrary/openlibrary/i18n/kn/strings.kn.yml on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
web_1        | failed to load strings from /openlibrary/openlibrary/i18n/kn/strings.kn.yml
web_1        | [2020-03-06 04:09:09 +0000] [62] [ERROR] Exception in worker process
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
web_1        |     worker.init_process()
web_1        |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 129, in init_process
web_1        |     self.load_wsgi()
web_1        |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
web_1        |     self.wsgi = self.app.wsgi()
web_1        |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
web_1        |     self.callable = self.load()
web_1        |   File "scripts/openlibrary-server", line 86, in load
web_1        |     infogami._setup()

```

Will need some investigation to see why these are even being loaded or parsed.

These were moved in the fix for #871 -- I thought this was just for storage, nothing should be reading them.
### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@tfmorris

**Comment by tfmorris** [comment]
Sorry, @mekarpeles must have missed this one when creating #3153 and I didn't notice it either when tied the fix to that issue. Closing as a duplicate.
