### ISSUE TITLE
MissingSchema(error) when starting up local docker

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#3141]
I'm not sure exactly what the code is trying to do yet, but it looks like it calling out to archive.org and failing -- is this missing config?

The erroring code is line 34:

https://github.com/internetarchive/openlibrary/blob/61e2b24738a31773be96a199361e085f2499e79d/openlibrary/core/ia.py#L23-L42

Last commit looks like it could b e relevant: https://github.com/internetarchive/openlibrary/commit/b0bdbff5a8a58a63536615dc97b58c0296ae2e2b#diff-76be93633d51ef7465bfa65e0eb27536

@cdrini any ideas?

### Evidence / Screenshot (if possible)
Errors on local Docker startup:
```
web_1        | 2020-03-06 04:04:24 [openlibrary.ia] [ERROR] Exception occurred accessing None/metadata/goldeneggboo00brow.
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/openlibrary/core/ia.py", line 34, in get_api_response
web_1        |     r = requests.get(url, params=params)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 75, in get
web_1        |     return request('get', url, params=params, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
web_1        |     return session.request(method=method, url=url, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 519, in request
web_1        |     prep = self.prepare_request(req)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 462, in prepare_request
web_1        |     hooks=merge_hooks(request.hooks, self.hooks),
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 313, in prepare
web_1        |     self.prepare_url(url, params)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 387, in prepare_url
web_1        |     raise MissingSchema(error)
web_1        | MissingSchema: Invalid URL 'None/metadata/goldeneggboo00brow': No schema supplied. Perhaps you meant http://None/metadata/goldeneggboo00brow?
```

```
web_1        | 2020-03-06 04:04:23 [infobase.cache] [DEBUG] MemcachedDict.update: ['/authors/OL3116481A']
web_1        | 2020-03-06 04:04:23 [openlibrary.solr.data_provider] [INFO] find_metadata html5-for-web-designers
web_1        | 2020-03-06 04:04:23 [openlibrary.ia] [ERROR] Exception occurred accessing None/metadata/html5-for-web-designers.
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/openlibrary/core/ia.py", line 34, in get_api_response
web_1        |     r = requests.get(url, params=params)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 75, in get
web_1        |     return request('get', url, params=params, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
web_1        |     return session.request(method=method, url=url, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 519, in request
web_1        |     prep = self.prepare_request(req)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 462, in prepare_request
web_1        |     hooks=merge_hooks(request.hooks, self.hooks),
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 313, in prepare
web_1        |     self.prepare_url(url, params)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 387, in prepare_url
web_1        |     raise MissingSchema(error)
web_1        | MissingSchema: Invalid URL 'None/metadata/html5-for-web-designers': No schema supplied. Perhaps you meant http://None/metadata/html5-for-web-designers?
```

```
web_1        | 2020-03-06 04:04:23 [openlibrary.ia] [ERROR] Exception occurred accessing None/metadata/greeneggsham00geis.
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/openlibrary/core/ia.py", line 34, in get_api_response
web_1        |     r = requests.get(url, params=params)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 75, in get
web_1        |     return request('get', url, params=params, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
web_1        |     return session.request(method=method, url=url, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 519, in request
web_1        |     prep = self.prepare_request(req)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 462, in prepare_request
web_1        |     hooks=merge_hooks(request.hooks, self.hooks),
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 313, in prepare
web_1        |     self.prepare_url(url, params)
web_1        |   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 387, in prepare_url
web_1        |     raise MissingSchema(error)
web_1        | MissingSchema: Invalid URL 'None/metadata/greeneggsham00geis': No schema supplied. Perhaps you meant http://None/metadata/greeneggsham00geis?
```
### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

**Comment by imskr** [comment]
I would like to work on this. Assign me.

**Comment by imskr** [comment]
This is likely because `http` or `https` is missing @hornc

**Comment by cclauss** [comment]
Confirmed again today on both Python 2 and Python 3.

**Comment by cclauss** [comment]
@cdrini What should this value be?  https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/ia.py#L19

**Comment by cclauss** [comment]
[__ia_base_url: https://archive.org__](https://github.com/internetarchive/openlibrary/blob/master/conf/openlibrary.yml#L174)

**Comment by hornc** [comment]
I'm no longer seeing any MissingSchema errors on Docker statup.
