### ISSUE TITLE
i18n Strings broadcasting SyntaxError on Server Start (possible regression) #3067

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3153]
@tfmorris + @hornc -- seeing some i18n `SyntaxErrors` on server start (on `dev`) possibly related to this branch:
```
/opt/openlibrary/venv/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSS
L project, please upgrade. The next version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
Traceback (most recent call last):
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
    data = read_strings(p)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
    execfile(path, env)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/it/strings.it.yml", line 3
    revision: 21
            ^
SyntaxError: invalid syntax
failed to load strings from /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/it/strings.it.yml
Traceback (most recent call last):
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
    data = read_strings(p)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
    execfile(path, env)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/kn/strings.kn.yml", line 2
SyntaxError: Non-ASCII character '\xe0' in file /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/kn/strings.kn.yml on line 2, but no encoding declared; see http://www.python.org/peps
/pep-0263.html for details
failed to load strings from /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/kn/strings.kn.yml
Traceback (most recent call last):
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
    data = read_strings(p)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
    execfile(path, env)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/mr/strings.mr.yml", line 2
SyntaxError: Non-ASCII character '\xe0' in file /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/mr/strings.mr.yml on line 2, but no encoding declared; see http://www.python.org/peps
/pep-0263.html for details
failed to load strings from /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/mr/strings.mr.yml
Traceback (most recent call last):
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
    data = read_strings(p)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
    execfile(path, env)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/nl/strings.nl.yml", line 3
    about_us: Over ons
            ^
SyntaxError: invalid syntax
failed to load strings from /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/nl/strings.nl.yml
Traceback (most recent call last):
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
    data = read_strings(p)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
    execfile(path, env)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/hi/strings.hi.yml", line 3
SyntaxError: Non-ASCII character '\xe0' in file /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/hi/strings.hi.yml on line 3, but no encoding declared; see http://www.python.org/peps
/pep-0263.html for details
failed to load strings from /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/hi/strings.hi.yml
2020-03-09 22:38:36 [29979] [openlibrary] [INFO] Application init
2020-03-09 22:38:36 [29979] [openlibrary] [INFO] loading plugin openlibrary
/opt/openlibrary/venv/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next ver
sion of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
/opt/openlibrary/venv/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSS
L project, please upgrade. The next version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
/opt/openlibrary/venv/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next ver
sion of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
Traceback (most recent call last):
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
    data = read_strings(p)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
    execfile(path, env)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/it/strings.it.yml", line 3
    revision: 21
            ^
SyntaxError: invalid syntax
failed to load strings from /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/it/strings.it.yml
Traceback (most recent call last):
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
    data = read_strings(p)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
    execfile(path, env)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/kn/strings.kn.yml", line 2
SyntaxError: Non-ASCII character '\xe0' in file /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/kn/strings.kn.yml on line 2, but no encoding declared; see http://www.python.org/peps
/pep-0263.html for details
failed to load strings from /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/kn/strings.kn.yml
Traceback (most recent call last):
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
    data = read_strings(p)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
    execfile(path, env)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/mr/strings.mr.yml", line 2
SyntaxError: Non-ASCII character '\xe0' in file /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/mr/strings.mr.yml on line 2, but no encoding declared; see http://www.python.org/peps
/pep-0263.html for details
failed to load strings from /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/mr/strings.mr.yml
Traceback (most recent call last):
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
    data = read_strings(p)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
    execfile(path, env)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/nl/strings.nl.yml", line 3
    about_us: Over ons
            ^
SyntaxError: invalid syntax
failed to load strings from /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/nl/strings.nl.yml
Traceback (most recent call last):
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 187, in load_strings
    data = read_strings(p)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py", line 178, in read_strings
    execfile(path, env)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/hi/strings.hi.yml", line 3
SyntaxError: Non-ASCII character '\xe0' in file /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/hi/strings.hi.yml on line 3, but no encoding declared; see http://www.python.org/peps
/pep-0263.html for details
failed to load strings from /opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/i18n/hi/strings.hi.yml
```

_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/pull/3067#issuecomment-596813132_

**Comment by tfmorris** [comment]
This is purely a cosmetic issue. Apparently the infogami i18n code attempts to load any files which match 'strings*' instead of restricting by file extension as one might expect. I'll rename the .yml files so that they are out of the way.
