### ISSUE TITLE
Investigate core.lending exceptions

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3429]
Core.lending seems to be erroring a lot. It definitely shouldn't be loading quite so many. Now that we have logs in place (thanks to @cclauss !), let's investigate!

Here's a dump from production of the sort of logs we're seeing:

```sh
grep -m200 -A20 -e 'core.lending.*ERROR' upstart.log | grep -v 'INFO'
```
Output: [core lending errors.txt](https://github.com/internetarchive/openlibrary/files/4566189/core.lending.errors.txt)

### Stakeholders
@cclauss @paulproteus @mekarpeles

**Comment by cdrini** [comment]
Here's an aggregate of error types:

```sh
$ grep -o -e '\[ERROR.*' core.lending.txt  | sed -r 's:\(.*?\):\(...\):' | sort | uniq -c
      4 [ERROR] Failed solr query
     12 [ERROR] Failed to get solr data
     69 [ERROR] get_availability(...)
     45 [ERROR] get_available(...)
     43 [ERROR] get_loan(...) 1 of 2
     43 [ERROR] get_loan(...) 2 of 2
```

`get_availability` might be a good target!

**Comment by mekarpeles** [comment]
```
2020-05-05 00:33:58 [30901] [openlibrary.core.lending] [ERROR] get_loan(belljar00plat) 2 of 2
Traceback (most recent call last):
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/core/lending.py", line 399, in get_loan
    _loan = _get_ia_loan(identifier, account and account.itemname)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/core/lending.py", line 408, in _get_ia_loan
    return ia_loan and Loan.from_ia_loan(ia_loan)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/core/lending.py", line 574, in from_ia_loan
    user_key = '/people/' + account.username
AttributeError: 'NoneType' object has no attribute 'username'
```

**Comment by paulproteus** [comment]
It looks to me like `get_loan()` is assuming someone is logged-in (i.e., `account` is non-`None`), but no one is logged in?
