### ISSUE TITLE
Python 3: get_sorted_editions() is not working on books/OL42679M

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3633]
Fixed by internetarchive/infogami#107

Look at the editions of The wit and wisdom of Mark Twain on Python 3.  http://staging.openlibrary.org/books/OL42679M

I have put debug code all around [get_sorted_editions()](https://github.com/internetarchive/openlibrary/search?q=get_sorted_editions) but have not found the fault.

 When this URL is opened, [openlibrary/templates/type/edition/view.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/edition/view.html#L13-L15) calls [get_sorted_editions()](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/models.py#L665)

Even when I `def get_sorted_editions(): return ['a', 'b', 'c']` an empty list [] is getting returned!

### Evidence / Screenshot (if possible)
<img width="961" alt="Screenshot 2020-07-29 at 17 31 10" src="https://user-images.githubusercontent.com/3709715/88821066-74b37500-d1c2-11ea-903d-d01d3fc14df7.png">

### Relevant url?

http://localhost:8080/books/OL42679M 
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/models.py#L665
called from https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/edition/view.html#L14 returns 8 editions on Python 2 but no editions on Python 3.

### Steps to Reproduce (Using changes in #3637 and internetarchive/infogami#104)

1.  docker-compose down ; INFOGAMI=local PYENV_VERSION=3.8.5 docker-compose up -d ; docker-compose logs -f --tail=10 web
2. Browser: `http://localhost:8080/books/OL42679M ` # no editions shown
3. Repeat 1. on PYENV_VERSION=2.7.6
4.  Browser: `http://localhost:8080/books/OL42679M`  # 8 editions shown

* Actual: No editions
* Expected: 8 editions

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cclauss** [comment]
On Python 2 the debugger shows
* work.get_sorted_editions is a `<bound method Work.get_sorted_editions of <Work: u'/works/OL53924W'>>`
On Python 3, it is nothing.

**Comment by aasifkhan7** [comment]
When I try to reproduce this, there are errors in infogami of print syntax after running `docker-compose up`. 
```
web_1        |   File "/openlibrary/infogami/__init__.py", line 72
web_1        |     print "Infogami Help"
web_1        |           ^
web_1        | SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Infogami Help")?
```
I guess it's because infogami is also getting interpreted as Python3. how did you work around this? @cclauss

**Comment by mekarpeles** [comment]
from call 2020-08-06 check lazyloading

**Comment by cclauss** [comment]
> print "Infogami Help"

Happens on Infogami master but disappears on internetarchive/infogami#104 `python3` branch.  Iy you have removed the # at the beginning of [this line](https://github.com/internetarchive/openlibrary/blob/master/docker-compose.yml#L31) and use this command to start up:
* docker-compose down ; INFOGAMI=local PYENV_VERSION=3.8.5 docker-compose up -d ; docker-compose logs -f --tail=10 web

**Comment by aasifkhan7** [comment]
Thanks! was able to reproduce this @cclauss. will look into it.

**Comment by aasifkhan7** [comment]
@cclauss I ran this through Postman http://127.0.0.1:8983/solr/select?wt=json&q=key%3A%22%2Fworks%2FOL42679M%22&start=0&fl=cover_edition_key%2Ccover_id%2Cedition_key%2Cfirst_publish_year%2Chas_fulltext%2Clending_edition_s%2Cchecked_out%2Cpublic_scan_b%2Cia as there must be a request to solr for the book `OL42679M`

it shows
```
{"responseHeader":{"status":0,"QTime":0,"params":{"wt":"json","q":"key:\"/works/OL42679M\"","start":"0","fl":"cover_edition_key,cover_id,edition_key,first_publish_year,has_fulltext,lending_edition_s,checked_out,public_scan_b,ia"}},"response":{"numFound":0,"start":0,"docs":[]}}
```

**Comment by cclauss** [comment]
```python
from pprint import pprint
pprint(postman_dict)
```
{'response': {'docs': [], 'numFound': 0, 'start': 0},
 'responseHeader': {'QTime': 0,
                    'params': {'fl': 'cover_edition_key,cover_id,edition_key,first_publish_year,has_fulltext,lending_edition_s,checked_out,public_scan_b,ia',
                               'q': 'key:"/works/OL42679M"',
                               'start': '0',
                               'wt': 'json'},
                    'status': 0}}

{'response': {'docs': [{'edition_key': ['OL2407849M',
                                        'OL2058361M',
                                        'OL23273793M',
                                        'OL1890025M',
                                        'OL8011987M',
                                        'OL7637879M',
                                        'OL42679M',
                                        'OL3421846M'],
                        'first_publish_year': 1987,
                        'has_fulltext': 'true',
                        'ia': ['witwisdomofmarkt00twai'],
                        'lending_edition_s': 'OL2058361M',
                        'public_scan_b': 'false'}],
              'numFound': 1,
              'start': 0},
 'responseHeader': {'QTime': 1,
                    'params': {'fl': 'cover_edition_key,cover_id,edition_key,first_publish_year,has_fulltext,lending_edition_s,checked_out,public_scan_b,ia',
                               'q': 'key:"/works/OL54120W"',
                               'start': '0',
                               'wt': 'json'},
                    'status': 0}}
```

**Comment by aasifkhan7** [comment]
@cclauss so we are getting the same results on the request!

**Comment by aasifkhan7** [comment]
@cclauss I tried to follow the stacktrace.
I realised that `/openlibrary/openlibrary/templates/type/work/view.html` is not getting called at all in case of http://127.0.0.1:8080/books/OL42679M - so the problem is not of [get_sorted_editions()](https://github.com/internetarchive/openlibrary/search?q=get_sorted_editions)

**Comment by aasifkhan7** [comment]
@cclauss logs in case of http://127.0.0.1:8080/books/OL42679M (somehow, the [get_sorted_editions()](https://github.com/internetarchive/openlibrary/search?q=get_sorted_editions) function is not even getting called !):
```
web_1        | 140702338987776: Call to __getattr__ on line 102 of /home/openlibrary/.pyenv/versions/3.8.5/lib/python3.8/site-packages/web/utils.py from line 10 of /openlibrary/openlibrary/templates/type/edition/view.html
web_1        | 140702338987776: Call to __getattr__ on line 823 of /openlibrary/infogami/infobase/client.py from line 14 of /openlibrary/openlibrary/templates/type/edition/view.html
web_1        | 140702338987776: Call to __getitem__ on line 776 of /openlibrary/infogami/infobase/client.py from line 839 of /openlibrary/infogami/infobase/client.py
web_1        | 140702338987776: Call to get on line 763 of /openlibrary/infogami/infobase/client.py from line 777 of /openlibrary/infogami/infobase/client.py
web_1        | 140702338987776: Call to _getdata on line 742 of /openlibrary/infogami/infobase/client.py from line 765 of /openlibrary/infogami/infobase/client.py
web_1        | 140702338987776: Call to __getattr__ on line 823 of /openlibrary/infogami/infobase/client.py from line 18 of /openlibrary/openlibrary/templates/type/edition/view.html
```

logs in case of http://127.0.0.1:8080/books/OL45310W :
```
web_1        | 140702338987776: Call to __getattr__ on line 102 of /home/openlibrary/.pyenv/versions/3.8.5/lib/python3.8/site-packages/web/utils.py from line 10 of /openlibrary/openlibrary/templates/type/work/view.html
web_1        | 140702338987776: Call to get_sorted_editions on line 665 of /openlibrary/openlibrary/plugins/upstream/models.py from line 18 of /openlibrary/openlibrary/templates/type/work/view.html
```

**Comment by cclauss** [comment]
This is correct.  It never gets called in Py3.  In fact in view.html, if you do `$ func = work.get_sorted_editions` then `func` will be `<bound method Work.get_sorted_editions of <Work: u'/works/OL53924W'>>` on Python 2 but will be `nothing` on Python 3.

**Comment by cdrini** [comment]
Here's a useful snippet we can use for testing this (py2). Note it errored here :P But I think it did "work". Let me try it in on py3

```
$ docker-compose exec web bash
root@3450f5c82794:/openlibrary# python
Python 2.7.6 (default, Jul 25 2020, 18:02:38)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import web; import infogami; from openlibrary.config import load_config; load_config('./config/openlibrary.yml'); infogami._setup()
2020-08-12 22:28:46 [infobase.ol] [INFO] logging initialized
2020-08-12 22:28:46 [infobase.ol] [DEBUG] debug
2020-08-12 22:28:46 [openlibrary.olbase] [INFO] setting up infobase events for Open Library
2020-08-12 22:28:47 [openlibrary] [INFO] Application init
2020-08-12 22:28:47 [openlibrary] [INFO] loading plugin openlibrary
2020-08-12 22:28:49 [openlibrary] [INFO] loading plugin search
2020-08-12 22:28:49 [openlibrary] [INFO] loading plugin worksearch
2020-08-12 22:28:50 [openlibrary] [INFO] loading plugin inside
2020-08-12 22:28:50 [openlibrary] [INFO] loading plugin books
2020-08-12 22:28:50 [openlibrary] [INFO] loading plugin admin
2020-08-12 22:28:50 [openlibrary] [INFO] loading plugin upstream
2020-08-12 22:28:50 [openlibrary] [INFO] loading plugin importapi
2020-08-12 22:28:50 [openlibrary] [INFO] loading plugin recaptcha
2020-08-12 22:28:50 [openlibrary] [INFO] loading complete.
2020-08-12 22:28:51 [infobase] [INFO] loading plugin openlibrary.olbase
2020-08-12 22:28:51 [infobase.ol] [INFO] logging initialized
2020-08-12 22:28:51 [infobase.ol] [DEBUG] debug
2020-08-12 22:28:51 [openlibrary.olbase] [INFO] setting up infobase events for Open Library
>>> web.ctx.site.get
<bound method Site.get of <infogami.infobase.client.Site instance at 0x3535c20>>
>>> web.ctx.site.get('/books/OL2058361M')
<Edition: 'The wit & wisdom of Mark Twain'>
>>> edition = web.ctx.site.get('/books/OL2058361M')
>>> edition.works
[<Thing: u'/works/OL54120W'>]
>>> edition.works[0]
<Thing: u'/works/OL54120W'>
>>> work = edition.works[0]
>>> work.get_sorted_editions()
2020-08-12 22:29:28 [openlibrary.logger] [INFO] solr request: http://solr:8080/solr/select?q=key%3A%22%2Fworks%2FOL54120W%22&start=0&wt=json&fl=cover_edition_key%2Ccover_id%2Cedition_key%2Cfirst_publish_year%2Chas_fulltext%2Clending_edition_s%2Cchecked_out%2Cpublic_scan_b%2Cia
2020-08-12 22:29:28 [infobase] [ERROR] Error in processing request GET /install
Traceback (most recent call last):
  File "infogami/infobase/server.py", line 81, in g
    d = f(self, *a, **kw)
  File "openlibrary/plugins/ol_infobase.py", line 141, in GET
    return count('edition_ref', '/type/edition', 'works', i.key)
  File "openlibrary/plugins/ol_infobase.py", line 124, in count
    pid = get_property_id(type, key)
  File "/home/openlibrary/.pyenv/versions/2.7.6/lib/python2.7/site-packages/web/utils.py", line 499, in __call__
    update(block=True)
  File "/home/openlibrary/.pyenv/versions/2.7.6/lib/python2.7/site-packages/web/utils.py", line 494, in update
    self.cache[key] = (self.func(*args, **keywords), time.time())
  File "openlibrary/plugins/ol_infobase.py", line 110, in get_property_id
    db = get_db()
  File "openlibrary/plugins/ol_infobase.py", line 106, in get_db
    return site.store.db
AttributeError: 'NoneType' object has no attribute 'store'
2020-08-12 22:29:28 [infobase.ol] [ERROR] Error
Traceback (most recent call last):
  File "infogami/infobase/server.py", line 81, in g
    d = f(self, *a, **kw)
  File "openlibrary/plugins/ol_infobase.py", line 141, in GET
    return count('edition_ref', '/type/edition', 'works', i.key)
  File "openlibrary/plugins/ol_infobase.py", line 124, in count
    pid = get_property_id(type, key)
  File "/home/openlibrary/.pyenv/versions/2.7.6/lib/python2.7/site-packages/web/utils.py", line 499, in __call__
    update(block=True)
  File "/home/openlibrary/.pyenv/versions/2.7.6/lib/python2.7/site-packages/web/utils.py", line 494, in update
    self.cache[key] = (self.func(*args, **keywords), time.time())
  File "openlibrary/plugins/ol_infobase.py", line 110, in get_property_id
    db = get_db()
  File "openlibrary/plugins/ol_infobase.py", line 106, in get_db
    return site.store.db
AttributeError: 'NoneType' object has no attribute 'store'
2020-08-12 22:29:28 [infobase.ol] [ERROR] Error saved to /var/log/openlibrary/infobase-errors/2020-08-12/infobase-222928.524825.html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "openlibrary/plugins/upstream/models.py", line 672, in get_sorted_editions
    len(self._solr_data.get('edition_key')) == self.edition_count
  File "openlibrary/core/cache.py", line 544, in g
    cache[key] = f(self, *args, **kwargs)
  File "openlibrary/core/cache.py", line 453, in func
    value = f(*args, **kwargs)
  File "openlibrary/core/models.py", line 478, in edition_count
    return self._site._request("/count_editions_by_work", data={"key": self.key})
  File "infogami/infobase/client.py", line 216, in _request
    out = self._conn.request(self.name, path, method, data)
  File "openlibrary/plugins/openlibrary/connection.py", line 62, in request
    return self.conn.request(sitename, path, method, data)
  File "openlibrary/plugins/openlibrary/connection.py", line 62, in request
    return self.conn.request(sitename, path, method, data)
  File "openlibrary/plugins/openlibrary/connection.py", line 62, in request
    return self.conn.request(sitename, path, method, data)
  File "openlibrary/plugins/openlibrary/connection.py", line 535, in request
    return self.reader.request(sitename, path, method, data=data)
  File "infogami/infobase/client.py", line 99, in request
    out = server.request(path, method, data)
  File "infogami/infobase/server.py", line 608, in request
    return tocall(*args)
  File "infogami/infobase/server.py", line 92, in g
    process_exception(common.InfobaseException(error="internal_error", message=str(e)))
  File "infogami/infobase/server.py", line 63, in process_exception
    raise web.HTTPError(status, {}, msg)
web.webapi.HTTPError: 500 Internal Server Error
>>> work.get_sorted_edition()

>>> work
<Work: u'/works/OL54120W'>
```

**Comment by cdrini** [comment]
Yep; python3 isn't handling type conversions of lazy objects; see how the item is still a `Thing` at the bottom.

```
$ docker-compose exec web bash
root@0206c0f14b4d:/openlibrary# python
Python 3.8.5 (default, Jul 25 2020, 18:05:38)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import web; import infogami; from openlibrary.config import load_config; load_config('./config/openlibrary.yml'); infogami._setup()
2020-08-12 22:43:40 [infobase.ol] [INFO] logging initialized
2020-08-12 22:43:40 [infobase.ol] [DEBUG] debug
2020-08-12 22:43:40 [openlibrary.olbase] [INFO] setting up infobase events for Open Library
2020-08-12 22:43:41 [openlibrary] [INFO] Application init
2020-08-12 22:43:41 [openlibrary] [INFO] loading plugin openlibrary
2020-08-12 22:43:43 [openlibrary] [INFO] loading plugin search
2020-08-12 22:43:43 [openlibrary] [INFO] loading plugin worksearch
2020-08-12 22:43:43 [openlibrary] [INFO] loading plugin inside
2020-08-12 22:43:43 [openlibrary] [INFO] loading plugin books
2020-08-12 22:43:43 [openlibrary] [INFO] loading plugin admin
2020-08-12 22:43:43 [openlibrary] [INFO] loading plugin upstream
2020-08-12 22:43:43 [openlibrary] [INFO] loading plugin importapi
2020-08-12 22:43:43 [openlibrary] [INFO] loading plugin recaptcha
2020-08-12 22:43:43 [openlibrary] [INFO] loading complete.
2020-08-12 22:43:43 [infobase] [INFO] loading plugin openlibrary.olbase
2020-08-12 22:43:43 [infobase.ol] [INFO] logging initialized
2020-08-12 22:43:43 [infobase.ol] [DEBUG] debug
2020-08-12 22:43:43 [openlibrary.olbase] [INFO] setting up infobase events for Open Library
>>> web.ctx.site.get('/books/OL2058361M')
<Edition: 'The wit & wisdom of Mark Twain'>
>>> edition = web.ctx.site.get('/books/OL2058361M')
>>> edition.works
[<Thing: '/works/OL54120W'>]
>>> edition.works[0]
<Thing: '/works/OL54120W'>
>>> work = edition.works[0]
>>> work.get_sorted_editions()

>>> work
<Thing: '/works/OL54120W'>
```

**Comment by cdrini** [comment]
I think this function might be the culprit:


https://github.com/internetarchive/infogami/blob/5f171aa4901c28ba89f6e38d97820440b8491ab4/infogami/infobase/client.py#L742-L749

```py
    def _getdata(self):
        if self._data is None:
            self._data = self._site._load(self.key, self._revision)

            # @@ Hack: change class based on type
            self.__class__ = _thing_class_registry.get(self._data.get('type').key, Thing)

        return self._data
```

**Comment by cdrini** [comment]
This comment here is what makes me think that might be the cause:

https://github.com/internetarchive/infogami/blob/5f171aa4901c28ba89f6e38d97820440b8491ab4/infogami/infobase/client.py#L823-L839

```py
        # Hack: __class__ of this object can change in _getdata method.
        #
        # Lets say __class__ is changed to A in _getdata and A has method foo.
        # When obj.foo() is called before initializing, foo won't be found because
        # __class__ is not yet set to A. Initialize and call getattr again to get
        # the expected behaviour.
```

**Comment by cclauss** [comment]
[`class Thing:`](https://github.com/internetarchive/infogami/blob/5f171aa4901c28ba89f6e38d97820440b8491ab4/infogami/infobase/client.py#L717) is an old style class in Python 2.  You can change it to a new style class in Python 2 with `class Thing(object):` and see what breaks.  Python 3 only has new style classes.

**Comment by cdrini** [comment]
Hmm, I tried switching python 2 to `class Thing(object)`, and it didn't have the same issue; maybe it's something related to the thing registry? But not sure.

```py
_thing_class_registry = {}
def register_thing_class(type, klass):
    _thing_class_registry[type] = klass
```

**Comment by cdrini** [comment]
I wonder if the `setup` functions are not being run! These should automagically run somehow.

https://github.com/internetarchive/openlibrary/blob/8c170ba788fd88d99f7006238a9b1fe698a2dfbb/openlibrary/plugins/upstream/models.py#L956-L974

**Comment by cdrini** [comment]
Nope; they're getting called; everything is getting called correctly. The retrieval of the class from the `thing_registry` is also succeeding. It's the assignment to `__class__` that's failing :(

**Comment by cdrini** [comment]
I dived in, and this is I _think_ the "correct" direction; but a ton of things break: https://github.com/internetarchive/infogami/pull/109 . Would love some feedback from y'all there (also @hornc !). The road does not look easy 😅

**Comment by cclauss** [comment]
What is the relationship between LazyObjects and Things? 

LazyObject has [the right approach](https://github.com/internetarchive/infogami/blob/f4bf178b9b654df4f8bc3fd9f352ab1e9f8eac24/infogami/infobase/client.py#L206)... It you ask a shallow object for an attribute (e.g. .get_sorted_editions()) that it does not have then it becomes a deep object on-the-fly and returns the requested attribute.
