### ISSUE TITLE
database not loading the data on running the openlibrary with docker

### ISSUE THREAD

**Issue by ArunTeltia** [internetarchive/openlibrary#3919]
when i am trying to launch localhost:8080 and In the home page i am getting this error 
 
![error](https://user-images.githubusercontent.com/43555219/96055363-73c8e000-0ea1-11eb-822c-1c2da6754595.JPG)

 
Here are the logs that I get on opening localhost:8080
```
db_1         | FATAL:  role "openlibrary" does not exist
web_1        | 2020-10-14 20:48:24 [infobase] [ERROR] Error in processing request GET /
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/infogami/infobase/server.py", line 79, in g
web_1        |     d = f(self, *a, **kw)
web_1        |   File "/openlibrary/infogami/infobase/server.py", line 211, in GET
web_1        |     json_data = site.get(i.key, revision=revision)
web_1        | AttributeError: 'NoneType' object has no attribute 'get'
web_1        | 2020-10-14 20:48:24 [infobase.ol] [ERROR] Error
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/infogami/infobase/server.py", line 79, in g
web_1        |     d = f(self, *a, **kw)
web_1        |   File "/openlibrary/infogami/infobase/server.py", line 211, in GET
web_1        |     json_data = site.get(i.key, revision=revision)
web_1        | AttributeError: 'NoneType' object has no attribute 'get'
web_1        | 2020-10-14 20:48:24 [infobase.ol] [ERROR] Error saved to /var/log/openlibrary/infobase-errors/2020-10-14/infobase-204824.141514.html
web_1        | error saved to /var/log/openlibrary/ol-errors/2020-10-14/204824142380.html
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/infogami/utils/template.py", line 144, in saferender
web_1        |     result = t(*a, **kw)
web_1        |   File "/home/openlibrary/.pyenv/versions/2.7.6/lib/python2.7/site-packages/web/template.py", line 881, in __call__
web_1        |     return BaseTemplate.__call__(self, *a, **kw)
web_1        |   File "/home/openlibrary/.pyenv/versions/2.7.6/lib/python2.7/site-packages/web/template.py", line 808, in __call__
web_1        |     return self.t(*a, **kw)
web_1        |   File "/openlibrary/openlibrary/templates/home/index.html", line 25, in __template__
web_1        |     $:render_template("home/custom_ia_carousel", title=_('Books We Love'), key="staff_picks", query='languageSorter:("English")', subject="openlibrary_staff_picks", sorts=["loans__status__last_loan_date desc"], limit=18, test=test)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/home.py", line 116, in get_cached_sponsorable_editions
web_1        |     timeout=dateutil.HOUR_SECS)())
web_1        |   File "/openlibrary/openlibrary/core/cache.py", line 110, in __call__
web_1        |     value, t = self.update(*args, **kw)
web_1        |   File "/openlibrary/openlibrary/core/cache.py", line 149, in update
web_1        |     value = self.f(*args, **kw)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/home.py", line 110, in get_cachable_sponsorable_editions
web_1        |     return [format_book_data(ed) for ed in get_sponsorable_editions()]
web_1        |   File "/openlibrary/openlibrary/core/sponsorships.py", line 47, in get_sponsorable_editions
web_1        |     candidates = web.ctx.site.get('/sponsorship/books').get('editions', [])
web_1        |   File "/openlibrary/infogami/infobase/client.py", line 319, in get
web_1        |     data = self._load(key, revision)
web_1        |   File "/openlibrary/infogami/infobase/client.py", line 267, in _load
web_1        |     data = self._get(key, revision)
web_1        |   File "/openlibrary/infogami/infobase/client.py", line 237, in _get
web_1        |     result = self._request('/get', data=data)
web_1        |   File "/openlibrary/infogami/infobase/client.py", line 223, in _request
web_1        |     out = self._conn.request(self.name, path, method, data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 34, in request
web_1        |     return self.get(sitename, data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 150, in get
web_1        |     return ConnectionMiddleware.get(self, sitename, data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 68, in get
web_1        |     return self.conn.request(sitename, '/get', 'GET', data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 34, in request
web_1        |     return self.get(sitename, data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 464, in get
web_1        |     response = ConnectionMiddleware.get(self, sitename, data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 68, in get
web_1        |     return self.conn.request(sitename, '/get', 'GET', data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 34, in request
web_1        |     return self.get(sitename, data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 292, in get
web_1        |     return result or ConnectionMiddleware.get(self, sitename, data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 68, in get
web_1        |     return self.conn.request(sitename, '/get', 'GET', data)
web_1        |   File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 535, in request
web_1        |     return self.reader.request(sitename, path, method, data=data)
web_1        |   File "/openlibrary/infogami/infobase/client.py", line 105, in request
web_1        |     out = server.request(path, method, data)
web_1        |   File "/openlibrary/infogami/infobase/server.py", line 598, in request
web_1        |     return tocall(*args)
web_1        |   File "/openlibrary/infogami/infobase/server.py", line 90, in g
web_1        |     process_exception(common.InfobaseException(error="internal_error", message=str(e)))
web_1        |   File "/openlibrary/infogami/infobase/server.py", line 61, in process_exception
web_1        |     raise web.HTTPError(status, {}, msg)
web_1        | HTTPError: 500 Internal Server Error
```
OS: Windows 10 
Error at the development side 

Stakeholder:
This is a docker issue so I guess
@cdrini

**Comment by mekarpeles** [comment]
@cclauss or @cdrini can you please decide who should own this issue and see if we can unblock @ArunTeltia? Thank you!

**Comment by mekarpeles** [comment]
@cclauss tagging you for now and making @cdrini the lead (in case he decides / or you need him to take over)

**Comment by cclauss** [comment]
I will try to Zoom with @ArunTeltia and see how this is set up.  `site is None` makes it difficult to do anything...

**Comment by ArunTeltia** [comment]
okay you can tell me when you want to do zoom meeting sir @cclauss

**Comment by ArunTeltia** [comment]
@cclauss sir i rebased my forked repo now when I docker-compose build and docker-compose up 
The log is showing this and the local environment is not setting up (not able to reach the page) 
```
$ docker-compose up
Starting openlibrary_memcached_1 ... done
Starting openlibrary_covers_1    ... done
Starting openlibrary_db_1        ... done
Starting openlibrary_solr_1      ... done
Starting openlibrary_home_1      ... done
Starting openlibrary_infobase_1  ... done
Starting openlibrary_web_1       ... done
Attaching to openlibrary_db_1, openlibrary_memcached_1, openlibrary_solr_1, openlibrary_covers_1, openlibrary_home_1, openlibrary_infobase_1, openlibrary_web_1
covers_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
db_1         | LOG:  database system was shut down at 2020-10-17 07:19:13 UTC
db_1         | LOG:  MultiXact member wraparound protections are now enabled
db_1         | LOG:  autovacuum launcher started
db_1         | LOG:  database system is ready to accept connections
home_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
infobase_1   | standard_init_linux.go:211: exec user process caused "no such file or directory"
solr_1       | /bin/sh: 1: /start.sh: not found
web_1        | standard_init_linux.go:211: exec user process caused "no such file or directory"
openlibrary_covers_1 exited with code 1
openlibrary_home_1 exited with code 1
openlibrary_infobase_1 exited with code 1
openlibrary_solr_1 exited with code 127
openlibrary_web_1 exited with code 1
```

**Comment by ArunTeltia** [comment]
@cclauss and i did a bit of pair programming and after rebuilding the docker container and docker-compose up it started without errors :D
