### ISSUE TITLE
Books with non-ascii titles erroring when clicked from search

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4033]
### Steps to Reproduce

1. Go to https://openlibrary.org/search?q=h%C3%A9las&mode=everything
2. Click on any book with a non-ascii character in the title

* Actual: 500 internal error on e.g. https://openlibrary.org/works/OL11565520W?edition=
* Expected: See the book

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF82
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@cclauss

**Comment by cclauss** [comment]
It is possible to raise similar errors by doing http://localhost:8080/books/add with Unicode characters:
```
0.08 (1): 200 POST /openlibrary.org/save_many {'query': '[{"title": "Life in L\\u00fcsai, Graub\\u00fcnden", "authors": [{"author": {"key": ""}}], "key": "/works/OL1W", "type": {"key": "/type/work"}}, {"works": [{"key": "/works/OL1W"}], "title": "Life in L\\u00fcsai, Graub\\u00fcnden", "publishers": ["\\u00d1an\\u00f8"], "publish_date": "2021", "key": "/books/OL5M", "type": {"key": "/type/edition"}}]', 'comment': 'Added new book.', 'action': 'add-book', 'data': '{}'}
[2020-11-06 12:06:26 +0000] [217] [ERROR] Error handling request /books/add
Traceback (most recent call last):
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
    resp.write(item)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 333, in write
    self.send_headers()
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 329, in send_headers
    util.write(self.sock, util.to_bytestring(header_str, "ascii"))
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/util.py", line 507, in to_bytestring
    return value.encode(encoding)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 250: ordinal not in range(128)
0.0 (1): SELECT * FROM store WHERE key='account/openlibrary6573'
```

**Comment by cclauss** [comment]
When `gunicorn` is updated to the current [v20.0.4](https://pypi.org/project/gunicorn) the exception changes to:
```
0.09 (1): 200 POST /openlibrary.org/save_many {'query': '[{"title": "\\u00fc", "authors": [{"author": {"key": ""}}], "key": "/works/OL1W", "type": {"key": "/type/work"}}, {"works": [{"key": "/works/OL1W"}], "title": "\\u00fc", "publishers": ["Nano"], "publish_date": "2021", "key": "/books/OL5M", "type": {"key": "/type/edition"}}]', 'comment': 'Added new book.', 'action': 'add-book', 'data': '{}'}
[2020-11-06 13:38:34 +0000] [215] [ERROR] Error handling request /books/OL5M/%FC/edit?mode=add-work
Traceback (most recent call last):
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/httpserver.py", line 271, in __call__
    return self.app(environ, start_response)
  File "/openlibrary/openlibrary/core/middleware.py", line 42, in __call__
    data = self.app(environ, new_start_response)
  File "scripts/openlibrary-server", line 118, in wrapper
    return app(environ, start_response)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 313, in wsgi
    self.load(env)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 457, in load
    ctx.path = env.get("PATH_INFO").encode("latin1").decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 12: invalid start byte
```

**Comment by cclauss** [comment]
Tried `environ['PATH_INFO'] = environ['PATH_INFO'].encode('utf-8').decode('latin1')` after line 117 of `openlibrary/scripts/openlibrary-server`

Looked at `normpath` in nfogami/infogami/utils/app.py

**Comment by cdrini** [comment]
Rolledback the deploy to resolve this issue over the weekend; we can find a fix next week before going back live.
