### ISSUE TITLE
Python 3: Sponsored carousel is not working

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4085]
Might be related: can't read it's memcache value from the admin UI:

### Evidence / Screenshot (if possible)
![Screenshot 2020-11-12 at 17 44 32](https://user-images.githubusercontent.com/3709715/98969618-51ad9680-250f-11eb-9e4a-7546bec29083.png)

### Relevant url?

https://openlibrary.org/admin/inspect/memcache?keys=books.sponsorable_editions-&action=read&debug=true

### Steps to Reproduce

* Actual: Permission denied.
* Expected: Access granted...

### Details

- **Logged in (Y/N)?** Yes
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Noticed this error (sensitive hidden), when I changed the error line from `logger.error` to `logger.exception`

```
web_1        | 2020-11-14 00:16:13 [198] [openlibrary.vendors] [ERROR] Failed to fetch amazon product
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/openlibrary/core/vendors.py", line 269, in _get_amazon_metadata
web_1        |     return amazon_api.get_product(id_, serialize=True, resources=resources)
web_1        |   File "/openlibrary/openlibrary/core/vendors.py", line 97, in get_product
web_1        |     products = self.get_products([asin], **kwargs)
web_1        |   File "/openlibrary/openlibrary/core/vendors.py", line 127, in get_products
web_1        |     response = self.api.get_items(request)
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/paapi5_python_sdk/api/default_api.py", line 169, in get_items
web_1        |     (data) = self.get_items_with_http_info(get_items_request, **kwargs)  # noqa: E501
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/paapi5_python_sdk/api/default_api.py", line 228, in get_items_with_http_info
web_1        |     return self.api_client.call_api(
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/paapi5_python_sdk/api_client.py", line 345, in call_api
web_1        |     return self.__call_api(resource_path, method, api_name,
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/paapi5_python_sdk/api_client.py", line 177, in __call_api
web_1        |     response_data = self.request(
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/paapi5_python_sdk/api_client.py", line 387, in request
web_1        |     return self.rest_client.POST(url,
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/paapi5_python_sdk/rest.py", line 279, in POST
web_1        |     return self.request("POST", url,
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/paapi5_python_sdk/rest.py", line 238, in request
web_1        |     raise ApiException(http_resp=r)
web_1        | paapi5_python_sdk.rest.ApiException: (429)
web_1        | Reason: Too Many Requests
web_1        | HTTP response headers: HTTPHeaderDict({'Server': 'Server', 'Date': 'Sat, 14 Nov 2020 00:16:13 GMT', 'Content-Type': 'application/json', 'Content-Length': '247', 'Connection': 'keep-alive', 'x-amz-rid': '************', 'x-amzn-RequestId': '**********', 'Vary': 'Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent'})
web_1        | HTTP response body: {"__type":"com.amazon.paapi5#TooManyRequestsException","Errors":[{"Code":"TooManyRequests","Message":"The request was denied due to request throttling. Please verify the number of requests made per second to the Amazon Product Advertising API."}]}
```

**Comment by cdrini** [comment]
Also noticed that neither Amazon or BWB are displaying prices on staging.openlibrary.org--but they are on dev! Are these APIs perhaps restricted to a set of IPs? And we need to add ol-web1/2 to those sets?

**Comment by cclauss** [comment]
> I changed the error line from logger.error to logger.exception.

Could you please make a PR for that change so that we no longer fail silently?

**Comment by cclauss** [comment]
#4097 fixes the TooManyRequestsException mentioned above and a `requests.content` (bytes) vs. `requests.text` (str) mixup but does not resolve this issue.

**Comment by cdrini** [comment]
Updated description with more examples. Note that the admin dashboard was fixed by initializing the ia tool on our web nodes; #4094 will fix that permanently.

**Comment by cdrini** [comment]
Reverted to py2 for now; dropping in priority

**Comment by cclauss** [comment]
Fixed by #4110
