### ISSUE TITLE
FutureWarning on xml.etree.ElementTree.Element.findall("//item")

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4162]
On both Python 2 and 3 [xml.etree.ElementTree.Element.findall("//item")](https://docs.python.org/3.9/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.findall) is raising `FutureWarning: This search is broken in 1.3 and earlier, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/item'` on [`openlibrary/plugins/upstream/utils.py#L744`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/utils.py#L744).

### Evidence / Screenshot (if possible)
https://sentry.archive.org/sentry/ol-web/issues/4528
```
2020-11-25 17:07:48 [213] [openlibrary.logger] [INFO] solr request: http://ol-solr1:8983/solr/select?wt=json&q=key%3A%22%2Fworks%2FOL50567W%22&start=0&fl=cover_edition_key%2Ccover_id%2Cedition_key%2Cfirst_publish_year%2Chas_fulltext%2Clending_edition_s%2Cchecked_out%2Cpublic_scan_b%2Cia
2020-11-25 17:07:48 [213] [openlibrary] [ERROR] Failed to get solr data
Traceback (most recent call last):
  File "/openlibrary/openlibrary/plugins/upstream/models.py", line 565, in _get_solr_data
    d = solr.select({"key": self.key}, fields=fields)
  File "/openlibrary/openlibrary/utils/solr.py", line 95, in select
    jsonData = requests.get(url, timeout=10).json()
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/openlibrary/openlibrary/plugins/upstream/utils.py:744: FutureWarning: This search is broken in 1.3 and earlier, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/item'
  return [parse_item(item) for item in tree.findall("//item")]
```

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
Do we know how/where this is impacting the patron experience? Is this happening during specific searches?

**Comment by mekarpeles** [comment]
This was last seen 3 months ago? Possibly resolved? Going to close and re-open if we see a resurgence. I know this is a lazy approach, sorry :(
