### ISSUE TITLE
scripts/copydocs.py fails on Python 3 w/ TypeError: POST data should be bytes

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4285]
### Evidence / Screenshot (if possible)

At first blush, this one seems easy to fix but it quickly bumps into #4212 !!

my Mac % `docker-compose exec web bash`
openlibrary@500abfd9a786:/openlibrary$ `./scripts/copydocs.py /books/OL21692921M`
```
Traceback (most recent call last):
  File "./scripts/copydocs.py", line 328, in <module>
    main()
  File "./scripts/copydocs.py", line 315, in main
    dest.login("admin", "admin123")
  File "/openlibrary/openlibrary/api.py", line 99, in login
    response = self._request('/account/login', method='POST', data=data, headers=headers)
  File "/openlibrary/openlibrary/api.py", line 55, in _request
    return urllib.request.urlopen(req)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/urllib/request.py", line 522, in open
    req = meth(req)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/urllib/request.py", line 1281, in do_request_
    raise TypeError(msg)
 an iterable of bytes, or a file object. It cannot be of type str.
```
### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cclauss** [comment]
@SouthGoingZax Could you please look into this one?

**Comment by SouthGoingZax** [comment]
Fixing the first problem also leads to:

```
During handling of the above exception, another exception occurred:
[...]
 File "/openlibrary/openlibrary/api.py", line 36, in __init__
    msg = http_error.msg + ": " + http_error.read()
TypeError: can only concatenate str (not "bytes") to str
```

Fixing that leads to the following, which looks like #4212, as @cclauss said.
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/copydocs.py", line 328, in <module>
    main()
  File "./scripts/copydocs.py", line 325, in main
    copy(src, dest, keys, comment=options.comment, recursive=options.recursive)
  File "./scripts/copydocs.py", line 255, in copy
    print(dest.save_many(docs, comment=comment))
  File "/openlibrary/openlibrary/api.py", line 154, in save_many
    return self._call_write('save_many', query, comment, action)
  File "/openlibrary/openlibrary/api.py", line 150, in _call_write
    response = self._request('/api/' + name, method="POST", data=simplejson.dumps(query), headers=headers)
  File "/openlibrary/openlibrary/api.py", line 59, in _request
    raise OLError(e)
openlibrary.api.OLError: Bad Request: {"error": "bad_data", "message": "Bad JSON: Expecting value: line 1 column 1 (char 0)"}
```

That error message comes from infobase/server.py in ```save_many.POST()```: https://github.com/infogami/infogami/blob/3e9357c0184cd51921e198762c9f7d03b4589cf1/infogami/infobase/server.py#L152.  

After a lot of digging, I can describe the problem and provide a work-around.

An example of data sent to infobase:
```
b'[{"subtitle": "l\'\\u00e9difice imaginaire : actes du 7e colloque du Centre d\'\\u00e9tudes cathares/Ren\\u00e9 Nelli, Carcassonne, 29 ao\\u00fbt-2 septembre 1994", "series": ["Heresis -- 7"], "lc_classifications": ["BX4876 .C38 1998"], "contributions": ["Berlioz, Jacques.", "H\\u00e9las, Jean-Claude.", "Centre national d\'\\u00e9tudes cathares (France)", "Session d\'histoire m\\u00e9di\\u00e9vale de Carcassonne (7th : 1994)"], "id": 32105711, "genres": ["Congresses."], "title": "Catharisme", "languages": [{"key": "/languages/fre"}], "subjects": ["Albigenses -- History -- Congresses.", "France -- Church history -- 987-1515 -- Congresses."], "publish_country": "fr ", "by_statement": "pre\\u015bent\\u00e9s par Jacques Berlioz et Jean-Claude H\\u00e9las ; traductions de Janice Valls Russel, Katja Roggenbuck et Anne Brenon.", "type": {"key": "/type/edition"}, "revision": 1, "publishers": ["Centre d\'\\u00e9tudes cathares"], "last_modified": {"type": "/type/datetime", "value": "2008-11-03T15:45:45.620829"}, "key": "/books/OL21692921M", "publish_places": ["[Villegly]"], "pagination": "478 p. :", "created": {"type": "/type/datetime", "value": "2008-11-03T15:45:45.620829"}, "notes": {"type": "/type/text", "value": "\\"7\\u00e8me session d\'histoire m\\u00e9di\\u00e9vale\\"--Cover.\\n\\nIncludes bibliographical references.\\n\\nSummaries in English and French."}, "number_of_pages": 478, "publish_date": "1998"}]'
```

You can manually copy that and paste it into a call to ```json.loads()```, and it will succeed.  However, in Infogami, in the POST() function mentioned above, for some reason the variable containing that data is a string object, not a bytes object.  But it's a string object with a byte literal inside of it.  You can't ```decode()``` it because strings don't have that method.  And when you pass such an object to ```json.loads()```:

```
>> d = b'[{"subtitle": "l\'\\u00e9difice imaginaire : actes du 7e colloque du Centre d\'\\u00e9tudes cathares/Ren\\u00e9 Nelli, Carcassonne, 29 ao\\u00fbt-2 septembre 1994", "series": ["Heresis -- 7"], "lc_classifications": ["BX4876 .C38 1998"], "contributions": ["Berlioz, Jacques.", "H\\u00e9las, Jean-Claude.", "Centre national d\'\\u00e9tudes cathares (France)", "Session d\'histoire m\\u00e9di\\u00e9vale de Carcassonne (7th : 1994)"], "id": 32105711, "genres": ["Congresses."], "title": "Catharisme", "languages": [{"key": "/languages/fre"}], "subjects": ["Albigenses -- History -- Congresses.", "France -- Church history -- 987-1515 -- Congresses."], "publish_country": "fr ", "by_statement": "pre\\u015bent\\u00e9s par Jacques Berlioz et Jean-Claude H\\u00e9las ; traductions de Janice Valls Russel, Katja Roggenbuck et Anne Brenon.", "type": {"key": "/type/edition"}, "revision": 1, "publishers": ["Centre d\'\\u00e9tudes cathares"], "last_modified": {"type": "/type/datetime", "value": "2008-11-03T15:45:45.620829"}, "key": "/books/OL21692921M", "publish_places": ["[Villegly]"], "pagination": "478 p. :", "created": {"type": "/type/datetime", "value": "2008-11-03T15:45:45.620829"}, "notes": {"type": "/type/text", "value": "\\"7\\u00e8me session d\'histoire m\\u00e9di\\u00e9vale\\"--Cover.\\n\\nIncludes bibliographical references.\\n\\nSummaries in English and French."}, "number_of_pages": 478, "publish_date": "1998"}]'
>>> type(d)
<class 'bytes'>
>>> json.loads(str(d))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

... you get the same error that copydocs.py is seeing.

Here's a work-around, which evals the string object, which returns a bytes object, and then ```decode()```s that:
```
iff --git a/infogami/infobase/server.py b/infogami/infobase/server.py
index 9667781..5f92031 100644
--- a/infogami/infobase/server.py
+++ b/infogami/infobase/server.py
@@ -5,6 +5,7 @@ from __future__ import print_function
 
 __version__ = "0.5dev"
 
+import ast
 import json
 import logging
 import os
@@ -240,7 +241,7 @@ class save_many:
     @jsonify
     def POST(self, sitename):
         i = input('query', comment=None, data=None, action=None)
-        docs = from_json(i.query)
+        docs = from_json(ast.literal_eval(i.query).decode())
         data = i.data and from_json(i.data)
         site = get_site(sitename)
         return site.save_many(docs, comment=i.comment, data=data, action=i.action)
```

Regarding a better fix, the POST() function uses [this ```input()``` function](https://github.com/infogami/infogami/blob/3e9357c0184cd51921e198762c9f7d03b4589cf1/infogami/infobase/server.py#L128) to get the data.  I'm not sure if there's a way to get a bytes object instead of a string from that function in a way that preserves that ```required``` and ```defaults``` functionality.

**Comment by cclauss** [comment]
I did more testing and found a problem on my wife’s book…
[`./scripts/copydocs.py /books/OL26617202M`](https://openlibrary.org/books/OL26617202M/La_Grande_Neige_(French_Edition))
