### ISSUE TITLE
Fresh install according to README hits Python 3 bug

### ISSUE THREAD

**Issue by tmcw** [internetarchive/openlibrary#4414]
### Evidence / Screenshot (if possible)

```
openlibrary_solr-updater_1 exited with code 1
solr-updater_1  | Python 3.8.6
solr-updater_1  | Traceback (most recent call last):
solr-updater_1  |   File "scripts/new-solr-updater.py", line 23, in <module>
solr-updater_1  |     from openlibrary.solr import update_work
solr-updater_1  |   File "/openlibrary/openlibrary/solr/update_work.py", line 18, in <module>
solr-updater_1  |     from infogami.infobase.client import ClientException
solr-updater_1  |   File "/openlibrary/infogami/__init__.py", line 72
solr-updater_1  |     print "Infogami Help"
solr-updater_1  |           ^
solr-updater_1  | SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Infogami Help")?
```

### Steps to Reproduce

1. Follow the [Docker README instructions](https://github.com/internetarchive/openlibrary/tree/master/docker)
2. Once you run `docker-compose up`, the above error message is produced

### Details

- **Logged in (Y/N)?**  N/A
- **Browser type/version?** N/A
- **Operating system?** macOS
- **Environment (prod/dev/local)?** dev

I found a relevant discussion in #2293, which points to a [python3 branch](https://github.com/internetarchive/openlibrary/tree/python3), which hasn't been updated since March 2020. It looks like the docker-based build went Python 3 by default in #4276.

I've made sure that:

- I've used the `ssh` protocol to check out the project
- Used `--recurse-submodules` when checking out (on a second run) to make sure that submodules were fetched.
- I pruned all docker data that could have been dangling around with `docker prune` and `docker prune -a`

In my local (macOS) filesystem, vendor/infogami/__init__.py has the correct syntax, `print("Infogami Help")`, but consistently, the version of that file in `/openlibrary/infogami/__init__.py` has this old Python syntax which causes it to crash.

**Comment by tmcw** [comment]
💥  I had pruned all the images, but there were still some volumes hanging around from 2 years ago, which were apparently getting reused when I tried this 'clean' install. Removing those volumes too clears up the issue.
