### ISSUE TITLE
Fix svgo and minify SVG assets

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#4746]
when running `npm run svg-min` i get:

```
/openlibrary/.svgo.yml:2
  - removeXMLProcInst: false
                     ^

SyntaxError: Unexpected token ':'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at importConfig (/openlibrary/node_modules/svgo/lib/svgo-node.js:12:18)
    at loadConfig (/openlibrary/node_modules/svgo/lib/svgo-node.js:33:20)
    at Command.action (/openlibrary/node_modules/svgo/lib/svgo/coa.js:105:32)
```

This should be fixed and we should minify all existing SVGs in the repo.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders
@jdlrobson

**Comment by ArunTeltia** [comment]
Can I work on this issue @jdlrobson

**Comment by shrey27tri01** [comment]
Any updates on this issue? Can I work on this?

Also, how should I go about fixing this? As far as I can see, I am unable to see an issue with the existing [svgo](https://github.com/svg/svgo) package in the repository. Also, I found [this](https://github.com/internetarchive/openlibrary/issues/1368) issue which implemented svg minification. Any pointers as to how to fix this would be helpful :sweat_smile:
