### ISSUE TITLE
`manage-imports.py` Archive.org ImportBot failing with `import-retro` mode

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5155]
### Evidence / Screenshot (if possible)

Running
```
python /openlibrary/scripts/manage-imports.py --config /olsystem/etc/openlibrary.yml import-retro
```

Results in error:

```
..., ('redacted'); SELECT currval('import_item_id_seq')
2021-05-07 23:59:10 [1236] [openlibrary.imports] [INFO] batch new-scans-202105: added 144392 items
0.5 (1): SELECT * FROM import_item WHERE batch_id = 272 AND status = 'pending'
2021-05-07 23:59:12 [1236] [openlibrary.importer] [INFO] importing redacted
2021-05-07 23:59:12 [1236] [openlibrary.api] [INFO] reading /root/.olrc
Traceback (most recent call last):
  File "/openlibrary/scripts/manage-imports.py", line 218, in <module>
    main()
  File "/openlibrary/scripts/manage-imports.py", line 200, in main
    return retroactive_import(start=start, stop=stop, servername=flags['servername'])
  File "/openlibrary/scripts/manage-imports.py", line 171, in retroactive_import
    do_import(item, servername=servername)
  File "/openlibrary/scripts/manage-imports.py", line 45, in do_import
    response = ol_import_request(item, servername=servername, require_marc=require_marc)
  File "/openlibrary/scripts/manage-imports.py", line 34, in ol_import_request
    ol = get_ol(servername=servername)
  File "/home/openlibrary/.pyenv/versions/3.9.4/lib/python3.9/site-packages/web/utils.py", line 510, in __call__
    update(block=True)
  File "/home/openlibrary/.pyenv/versions/3.9.4/lib/python3.9/site-packages/web/utils.py", line 505, in update
    self.cache[key] = (self.func(*args, **keywords), time.time())
  File "/openlibrary/scripts/manage-imports.py", line 21, in get_ol
    ol.autologin()
  File "/openlibrary/openlibrary/api.py", line 90, in autologin
    raise Exception("No section found with name %s in ~/.olrc" % repr(section))
Exception: No section found with name 'openlibrary.org' in ~/.olrc
```

### Related files

`scripts/manage-imports.py`

### Stakeholders

@cdrini, @hornc

**Comment by mekarpeles** [comment]
The file that we want seems to be in `/opt/olsystem/etc/olrc-importbot`

**Comment by mekarpeles** [comment]
![openlibrary org_admin_imports (2)](https://user-images.githubusercontent.com/978325/117521484-e515d080-af62-11eb-9e07-df6dec358a20.png)

Success!
