### ISSUE TITLE
Open Library Stats Cron hitting Document update conflict

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6439]
```
Traceback (most recent call last):
  File "/openlibrary/scripts/store_counts.py", line 18, in <module>
    sys.exit(stats.main(*sys.argv[1:]))
  File "/openlibrary/openlibrary/admin/stats.py", line 168, in main
    store_data(data, today.strftime("%Y-%m-%d"))
  File "/openlibrary/openlibrary/admin/stats.py", line 68, in store_data
    web.ctx.site.store[uid] = doc
  File "/openlibrary/infogami/infobase/client.py", line 630, in __setitem__
    return self._request(key, method='PUT', data=json.dumps(data))
  File "/openlibrary/infogami/infobase/client.py", line 569, in _request
    out = self.conn.request(self.name, "/_store/" + path, method, data)
  File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 54, in request
    return self.store_put(sitename, path, data)
  File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 101, in store_put
    return self.conn.request(sitename, path, 'PUT', data)
  File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 54, in request
    return self.store_put(sitename, path, data)
  File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 101, in store_put
    return self.conn.request(sitename, path, 'PUT', data)
  File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 54, in request
    return self.store_put(sitename, path, data)
  File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 392, in store_put
    result = ConnectionMiddleware.store_put(self, sitename, path, data)
  File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 101, in store_put
    return self.conn.request(sitename, path, 'PUT', data)
  File "/openlibrary/openlibrary/plugins/openlibrary/connection.py", line 570, in request
    return self.writer.request(sitename, path, method, data=data)
  File "/openlibrary/infogami/infobase/client.py", line 197, in request
    self.handle_error(
  File "/openlibrary/infogami/infobase/client.py", line 91, in handle_error
    raise ClientException(status, message, json_data)
infogami.infobase.client.ClientException: Document update conflict
```

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Still looks a little funky; but works correctly when we backfill it by running it manually for 30 days.

**Comment by mekarpeles** [comment]
we needed to add `doc["_rev"] = None` to line 67 on `/openlibrary/openlibrary/admin/stats.py` to avoid the revision from conflicting between scripts.
