### ISSUE TITLE
The "docker compose exec -uroot ..." in i18n's README " doesn't work if the instructions are followed

### ISSUE THREAD

**Issue by cacaoMath** [internetarchive/openlibrary#8002]
Sorry for my poor English.
### Evidence / Screenshot (if possible)

```shell
$ sudo docker compose up -d
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string. 
[+] Running 8/8
 ⠿ Container openlibrary-home-1          Started                                                                                                                                                                              0.4s
 ⠿ Container openlibrary-memcached-1     Running                                                                                                                                                                              0.0s
 ⠿ Container openlibrary-db-1            Running                                                                                                                                                                              0.0s
 ⠿ Container openlibrary-solr-updater-1  Running                                                                                                                                                                              0.0s
 ⠿ Container openlibrary-solr-1          Running                                                                                                                                                                              0.0s
 ⠿ Container openlibrary-infobase-1      Running                                                                                                                                                                              0.0s
 ⠿ Container openlibrary-covers-1        Running                                                                                                                                                                              0.0s
 ⠿ Container openlibrary-web-1           Running                                                                                                                                                                              0.0s
$ sudo docker compose run --rm -uroot home ./scripts/i18n-messages update ja
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string. 
Traceback (most recent call last):
  File "/openlibrary/./scripts/i18n-messages", line 8, in <module>
    from openlibrary import i18n
  File "/openlibrary/openlibrary/i18n/__init__.py", line 4, in <module>
    import web
ModuleNotFoundError: No module named 'web'
```
Same for other commands.
```sh
$ docker compose exec -uroot web ./scripts/i18n-messages add [CODE]
$ docker compose exec -uroot web ./scripts/i18n-messages validate [CODE]
$ docker compose exec -uroot web ./scripts/i18n-messages validate [CODE]
$ docker compose run --rm -uroot home ./scripts/i18n-messages extract
```

### Relevant url?
https://github.com/internetarchive/openlibrary/tree/master/openlibrary/i18n#updating-an-existing-language

### Steps to Reproduce

I noticed that when I decided to try to translate Japanese.
[Followed here.](https://github.com/internetarchive/openlibrary/tree/master/openlibrary/i18n#updating-an-existing-language)
1. Run `docker compose up -d`
2. [The Japanese file](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/ja/messages.po) existed, so I tried to update it. Run `docker compose exec -uroot web ./scripts/i18n-messages validate ja`

* Actual:  `ModuleNotFoundError: No module named 'web'`
```sh
$ sudo docker compose run --rm -uroot home ./scripts/i18n-messages update ja
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string. 
Traceback (most recent call last):
  File "/openlibrary/./scripts/i18n-messages", line 8, in <module>
    from openlibrary import i18n
  File "/openlibrary/openlibrary/i18n/__init__.py", line 4, in <module>
    import web
ModuleNotFoundError: No module named 'web'
```
* Expected:　Operate successfully
```sh
$ sudo docker compose run --rm -uroot home ./scripts/i18n-messages update ja
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string. 
updated /openlibrary/openlibrary/i18n/ja/messages.po
compiled /openlibrary/openlibrary/i18n/ja/messages.po
```
### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
  -  Ubuntu 22.04.1 (wsl2)
- **Environment (prod/dev/local)?** local

### Proposal & Constraints

In the Dockerfile, the "PATH" of the "web.py" module is missing for the root user because requirements.txt is installed for the openlibrary user.

https://github.com/internetarchive/openlibrary/blob/32856721c9ee14f187668c339377e33bc8b57dc4/docker/Dockerfile.olbase#L68-L71

```shell
$ sudo docker compose run --rm -uroot home bash
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string. 
root@6c19007a0d66:/openlibrary# pip list
Package    Version
---------- -------
pip        22.3.1
setuptools 65.5.1
wheel      0.38.4
root@6c19007a0d66:/openlibrary# python              
Python 3.11.1 (main, Jan 11 2023, 14:30:50) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/local/lib/python311.zip', '/usr/local/lib/python3.11', '/usr/local/lib/python3.11/lib-dynload', '/usr/local/lib/python3.11/site-packages']
>>> exit()
root@6c19007a0d66:/openlibrary# su openlibrary
$ python
Python 3.11.1 (main, Jan 11 2023, 14:30:50) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/local/lib/python311.zip', '/usr/local/lib/python3.11', '/usr/local/lib/python3.11/lib-dynload', '/home/openlibrary/.local/lib/python3.11/site-packages', '/usr/local/lib/python3.11/site-packages']
>>> exit()
```

Therefore I think we need to modify the i18 README procedure to show "PYTHONPATH" or change the Dockerfile settings. To make it easier for future translators to make it work.

Set "-e PYTHONPATH" to work as follows, it become to works.
```sh
$ sudo docker compose run --rm -uroot -e PYTHONPATH='/home/openlibrary/.local/lib/python3.11/site-packages' home ./scripts/i18n-messages update ja
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string. 
updated /openlibrary/openlibrary/i18n/ja/messages.po
compiled /openlibrary/openlibrary/i18n/ja/messages.po
```

**Comment by scottbarnes** [comment]
Thank you @cacaoMath for the thorough research into the options here. If only more issues were as well laid out as this one. :)
