### ISSUE TITLE
Recent changes to solr-updater breaking solr updating

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#876]
```
==> default: Traceback (most recent call last):
==> default:   File "openlibrary/solr/update_work.py", line 1842, in <module>
==> default:
==> default: main()
==> default:   File "openlibrary/solr/update_work.py", line 1830, in main
==> default:
==> default: load_configs(args.server, args.config, args.data_provdider)
==> default: AttributeError
==> default: :
==> default: 'Namespace' object has no attribute 'data_provdider'
==> default: make: *** [reindex-solr] Error 123
```

I am creating a hotfix now, cc: @hornc, @cdrini

**Comment by tfmorris** [comment]
So what do we need to change in our processes / tooling to keep things like this from happening?
