### ISSUE TITLE
Change "Thriller" query on homepage

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#9043]
### Problem

The Thriller carousel on the homepage queries specific authors which means the same works always appear, and also non-thrillers appear by those authors. 

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Proposal & constraints

Change the query to https://archive.org/search?query=openlibrary_work%3A%28*%29+AND+collection%3A%28inlibrary%29+AND+%28lending___available_to_browse%3Atrue+OR+lending___available_to_borrow%3Atrue%29+AND+%28%22thriller%22%29&sort=-downloads.

**Comment by tfmorris** [comment]
Wouldn't it be better to query OpenLibrary than Internet Archive? The first scanned volume that that query returns is included because a user review includes the word "thriller" which seems like a dubious inclusion criterium.

**Comment by cdrini** [comment]
What about this? https://openlibrary.org/search?q=subject%3Athrillers+ratings_count%3A%5B5+TO+%2A%5D&mode=everything&sort=random

**Comment by tfmorris** [comment]
It timed out 2/3 times that I tried it, but modulo that, I think it's an improvement.

**Comment by seabelis** [comment]
Error. 
Hmm...
Sorry. There seems to be a problem with what you were just looking at.

We've noted the error 2024-04-10/152624830521 and will look into it as soon as possible. Head for [home](https://openlibrary.org/)?

**Comment by cdrini** [comment]
Gah sorry folks I made a typo in my url! That's what I get for trying to change the url directly :P I fixed it it should work now.

**Comment by seabelis** [comment]
Better. Let's do ratings_count:[2 TO *]. I'm pretty sure someone added a bunch of 1 star ratings to lots of items right when we launched that feature.

**Comment by seabelis** [comment]
<img width="1085" alt="Screenshot 2024-08-19 at 18 37 47" src="https://github.com/user-attachments/assets/08e3b05b-ac50-4860-9552-5eadcaa0f84a">
Four out of six of these titles are not thrillers.

**Comment by mekarpeles** [comment]
`subject:thrillers ratings_count:[10 TO *] ebook_access:[borrowable TO *]`

This query should be removed
https://github.com/internetarchive/openlibrary/blob/06fe991e78d543ae0dd42a6dbaece5a126883ba5/openlibrary/plugins/openlibrary/home.py#L20-L26

Replace the ia query here
https://github.com/internetarchive/openlibrary/blob/06fe991e78d543ae0dd42a6dbaece5a126883ba5/openlibrary/templates/home/index.html#L35
with
```
$:macros.QueryCarousel(query="subject:thrillers ratings_count:[10 TO *] ebook_access:[borrowable TO *]", title=_('Thrillers'), key="thrillers", url="/subjects/thrillers", sort='random.hourly', use_cache=False)
```

**Comment by shreeramansrinivasan** [comment]
I am new here. Is this fixed ? Because I can see that the thriller carousel looks okay. If it is still not fixed, can I work on this ?

**Comment by shreeramansrinivasan** [comment]
Thanks @mekarpeles . Let me take a stab at this.

**Comment by shreeramansrinivasan** [comment]
May be dumb question, but when I try running docker compose up, I see only the dev version of the website popping up. How can I generate the production version or something more than the dev version locally ? I tried searching for information about it online or in the wiki and somehow missing it. 
Also, how are you guys getting different version of the thriller carousel for the above mentioned screenshots ? I am assuming you are running better than the dev version locally (?). Thanks !

**Comment by shreeramansrinivasan** [comment]
I found a way to get the carousel headers in the development version by forcing `    page = render_template("home/index", stats=stats, blog_posts=blog_posts, test = True)
`
but that still doesnt render the books. I will keep plodding on that front.

**Comment by shreeramansrinivasan** [comment]
Also, I made the changes you suggested, @mekarpeles on a local branch, following the suggestions under https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request. 
But I am not able to push my changes . I get this error even after I have authenticated github multiple times. 
```
remote: Permission to internetarchive/openlibrary.git denied to shreeramansrinivasan.
fatal: unable to access 'https://github.com/internetarchive/openlibrary.git/': The requested URL returned error: 403
```
Any suggestions ?

**Comment by mekarpeles** [comment]
Thank you @shreeramansrinivasan! On https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet the first 3 steps are:

1. [Forking and Cloning the Open Library Repository](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#forking-and-cloning-the-open-library-repository)
2. [Working on Your Branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch)
3. [Making Changes and Creating a Pull Request](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request)

Is it possible step #1 may have been skipped? :)

**Comment by shreeramansrinivasan** [comment]
Thanks ! I probably just downloaded the repo then. Let me fork it first and retry.

**Comment by shreeramansrinivasan** [comment]
Thanks @mekarpeles , i forked the repo this time and cloned it locally. I am trying to get the local version of open library running. 
I encountered problems related to the stuff mentioned in troubleshooting 
https://github.com/internetarchive/openlibrary/tree/master/docker#fully-resetting-your-environment
which I tried to resolve by running the commands mentioned in troubleshooting. 
But when I run docker compose up , I run into the following error even after resetting the full environment 
`| 172.18.0.3:51010 - - [02/Mar/2025 00:21:00] "HTTP/1.1 GET /openlibrary.org/log/2025-03-02:0" - 200 OK
2025-03-01 16:21:05 infobase-1      | 172.18.0.3:51018 - - [02/Mar/2025 00:21:05] "HTTP/1.1 GET /openlibrary.org/log/2025-03-02:0" - 200 OK
2025-03-01 16:21:05 db-1            | FATAL:  role "openlibrary" does not exist
2025-03-01 16:21:05 web-1           | 2025-03-02 00:21:05 [infobase] [ERROR] Error in processing request GET /
2025-03-01 16:21:05 web-1           | Traceback (most recent call last):
2025-03-01 16:21:05 web-1           |   File "/openlibrary/infogami/infobase/server.py", line 103, in g
2025-03-01 16:21:05 web-1           |     d = f(self, *a, **kw)
2025-03-01 16:21:05 web-1           |         ^^^^^^^^^^^^^^^^^
2025-03-01 16:21:05 web-1           |   File "/openlibrary/infogami/infobase/server.py", line 452, in delegate
2025-03-01 16:21:05 web-1           |     raise RuntimeError(f"get_site({sitename}) failed")
2025-03-01 16:21:05 web-1           | RuntimeError: get_site(openlibrary.org) failed
2025-03-01 16:21:05 web-1           | 2025-03-02 00:21:05 [infobase.ol] [ERROR] Error
2025-03-01 16:21:05 web-1           | Traceback (most recent call last):
2025-03-01 16:21:05 web-1           |   File "/openlibrary/infogami/infobase/server.py", line 103, in g
2025-03-01 16:21:05 web-1           |     d = f(self, *a, **kw)
2025-03-01 16:21:05 web-1           |         ^^^^^^^^^^^^^^^^^
2025-03-01 16:21:05 web-1           |   File "/openlibrary/infogami/infobase/server.py", line 452, in delegate
2025-03-01 16:21:05 web-1           |     raise RuntimeError(f"get_site({sitename}) failed")
2025-03-01 16:21:05 web-1           | RuntimeError: get_site(openlibrary.org) failed
2025-03-01 16:21:05 web-1           | 2025-03-02 00:21:05 [infobase.ol] [ERROR] Error saved to /var/log/openlibrary/infobase/errorlog/2025-03-02/infobase-002105.897972.html
2025-03-01 16:21:10 infobase-1      | 172.18.0.3:35794 - - [02/Mar/2025 00:21:10] "HTTP/1.1 GET /openlibrary.org/log/2025-03-`

**Comment by mekarpeles** [comment]
Nice job following the docker guide for Windows!

Fun fact -- you could have kept your existing docker setup and simply changed the `remote origin` of your repo to point to your fork (and not had to make any code or repo changes since the code of your fork and the original codebase should have been the same).

This would have been done by going into the origin openlibrary repo and updating the `origin` remote url as follows:
```
git remote set-url origin git@github.com:shreeramansrinivasan/openlibrary.git
git remote show origin # confirm it worked
```

This seems like a similar problem to this issue https://github.com/internetarchive/openlibrary/issues/3919#issuecomment-711286382 whose solution has been documented here:

https://github.com/internetarchive/openlibrary/blob/master/docker/README.md#an-error-similar-to-fatal-role-openlibrary-does-not-exist

**Comment by shreeramansrinivasan** [comment]
Thanks @mekarpeles , I was able to get away with pointing my remote to the forked repository. Resetting the environment dint help for the other cloned repo I created. 
#10532 , created a PR with changes you mentioned. I will work on testing the changes, but I guess I still dont know how to get a production-esque version to run locally. Any comments on that front would be much appreciated. 
Thanks @mekarpeles for all the help  !

**Comment by shreeramansrinivasan** [comment]
HI @mekarpeles , is it possible to add me to the slack channel ? I have some questions that I will feel can be better posted in the slack channel.
