### ISSUE TITLE
OL depends on python-argparse-1.2 but installs 1.1

### ISSUE THREAD

**Issue by rwst** [internetarchive/openlibrary#93]
```
$ sudo python setup.py bootstrap
running bootstrap
reading config file config/install.ini
creating virtualenv at /Users/ralfstephan/pyenvs/ol
installing python dependencies
installing http://www.archive.org/download/ol_vendor/python-meld3-0.6.7.tar.gz
...
installing http://www.archive.org/download/ol_vendor/python-argparse-1.1.zip
...
installing remaining packages
Traceback (most recent call last):
File "scripts/setup_dev_instance.py", line 770, in <module>
install()
File "scripts/setup_dev_instance.py", line 656, in install
task.run()
File "scripts/setup_dev_instance.py", line 313, in run
system(INTERP + " setup.py develop")
File "scripts/setup_dev_instance.py", line 106, in system
raise Exception("%r failed with exit code %d" % (cmd, ret))
Exception: '/Users/rwst/pyenvs/ol/bin/python setup.py develop' failed with exit code 256
```

so I did:

```
$ sudo ../pyenvs/ol/bin/python setup.py develop
running develop
running egg_info
writing requirements to openlibrary.egg-info/requires.txt
...
Installing upstream-adapter script to /Users/rwst/pyenvs/ol/bin
Installing view_marc.py script to /Users/rwst/pyenvs/ol/bin

Installed /Users/rwst/openlibrary
Processing dependencies for openlibrary==2.0
error: Installed distribution argparse 1.1 conflicts with requirement argparse>=1.2
```

**Comment by rohitjain00** [comment]
Is there any follow up? or do this Issue needs to be closed?

**Comment by brad2014** [comment]
@mekarpeles , I recommend we close.

**Comment by guyjeangilles** [comment]
Closing based on the above evidence that this isn't a problem anymore.
