### ISSUE TITLE
Solr fails upon trying to reindex a document on the localHost

### ISSUE THREAD

**Issue by benbdeitch** [internetarchive/openlibrary#9536]
### Problem

When entering individual keys in the Admin Solr endpoint,  it fails to manually update the index of the given key.  This also fails upon the automatic reindex after an author or work's data is edited.
#### Evidence / Screenshot
```2024-07-08 18:26:15 2024-07-08 22:26:15 [openlibrary.solr.data_provider] [INFO] preload_documents0 ['/authors/OL18319A']
2024-07-08 18:26:19 0.01 (52): SELECT thing.key, data.data from thing, data WHERE data.revision = thing.latest_revision and data.thing_id=thing.id  AND thing.key IN ('/authors/OL18319A')
2024-07-08 18:26:19 2024-07-08 22:26:19 [openlibrary.solr.data_provider] [INFO] preload_redirects ['/authors/OL18319A']
2024-07-08 18:26:23 0.0 (53): SELECT * FROM thing WHERE key='/type/redirect'
2024-07-08 18:26:23 0.0 (54): SELECT data FROM data WHERE thing_id=17 AND revision=2
2024-07-08 18:26:23 0.0 (55): SELECT * FROM thing WHERE key='/type/string'
2024-07-08 18:26:23 0.0 (56): SELECT data FROM data WHERE thing_id=3 AND revision=1
2024-07-08 18:26:23 0.0 (57): SELECT * FROM thing WHERE key='/type/property'
2024-07-08 18:26:23 0.0 (58): SELECT data FROM data WHERE thing_id=9 AND revision=2
2024-07-08 18:26:23 0.0 (59): SELECT * FROM thing WHERE key='/type/redirect'
2024-07-08 18:26:23 0.0 (60): SELECT * FROM thing WHERE key='/type/redirect'
2024-07-08 18:26:23 0.0 (61): SELECT set_config('statement_timeout', '60000', false)
2024-07-08 18:26:23 0.01 (62): SELECT d0.thing_id FROM datum_str as d0 WHERE d0.key_id=139 AND d0.value = '/authors/OL18319A' LIMIT 20 OFFSET 0
2024-07-08 18:26:23 2024-07-08 22:26:23 [infobase.cache] [DEBUG] MemcachedDict.update: ['/type/redirect', '/type/string', '/type/property']
2024-07-08 18:26:27 2024-07-08 22:26:27 [openlibrary.solr] [ERROR] Failed to update '/authors/OL18319A'
2024-07-08 18:26:27 Traceback (most recent call last):
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/anyio/_core/_sockets.py", line 192, in connect_tcp
2024-07-08 18:26:27     addr_obj = ip_address(remote_host)
2024-07-08 18:26:27                ^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/usr/local/lib/python3.12/ipaddress.py", line 54, in ip_address
2024-07-08 18:26:27     raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
2024-07-08 18:26:27 ValueError: 'solr' does not appear to be an IPv4 or IPv6 address
2024-07-08 18:26:27 
2024-07-08 18:26:27 During handling of the above exception, another exception occurred:
2024-07-08 18:26:27 
2024-07-08 18:26:27 Traceback (most recent call last):
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
2024-07-08 18:26:27     yield
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
2024-07-08 18:26:27     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
2024-07-08 18:26:27                                    ^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/anyio/_core/_sockets.py", line 195, in connect_tcp
2024-07-08 18:26:27     gai_res = await getaddrinfo(
2024-07-08 18:26:27               ^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/anyio/_core/_sockets.py", line 573, in getaddrinfo
2024-07-08 18:26:27     gai_res = await get_async_backend().getaddrinfo(
2024-07-08 18:26:27               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2370, in getaddrinfo
2024-07-08 18:26:27     return await get_running_loop().getaddrinfo(
2024-07-08 18:26:27            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 899, in getaddrinfo
2024-07-08 18:26:27     return await self.run_in_executor(
2024-07-08 18:26:27            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
2024-07-08 18:26:27     result = self.fn(*self.args, **self.kwargs)
2024-07-08 18:26:27              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/usr/local/lib/python3.12/socket.py", line 963, in getaddrinfo
2024-07-08 18:26:27     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2024-07-08 18:26:27                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27 socket.gaierror: [Errno -2] Name or service not known
2024-07-08 18:26:27 
2024-07-08 18:26:27 The above exception was the direct cause of the following exception:
2024-07-08 18:26:27 
2024-07-08 18:26:27 Traceback (most recent call last):
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
2024-07-08 18:26:27     yield
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
2024-07-08 18:26:27     resp = await self._pool.handle_async_request(req)
2024-07-08 18:26:27            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
2024-07-08 18:26:27     raise exc
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
2024-07-08 18:26:27     response = await connection.handle_async_request(request)
2024-07-08 18:26:27                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
2024-07-08 18:26:27     raise exc
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
2024-07-08 18:26:27     stream = await self._connect(request)
2024-07-08 18:26:27              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 117, in _connect
2024-07-08 18:26:27     stream = await self._network_backend.connect_tcp(**kwargs)
2024-07-08 18:26:27              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
2024-07-08 18:26:27     return await self._backend.connect_tcp(
2024-07-08 18:26:27            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 112, in connect_tcp
2024-07-08 18:26:27     with map_exceptions(exc_map):
2024-07-08 18:26:27   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
2024-07-08 18:26:27     self.gen.throw(value)
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-07-08 18:26:27     raise to_exc(exc) from exc
2024-07-08 18:26:27 httpcore.ConnectError: [Errno -2] Name or service not known
2024-07-08 18:26:27 
2024-07-08 18:26:27 The above exception was the direct cause of the following exception:
2024-07-08 18:26:27 
2024-07-08 18:26:27 Traceback (most recent call last):
2024-07-08 18:26:27   File "/openlibrary/openlibrary/solr/update.py", line 107, in update_keys
2024-07-08 18:26:27     new_update_state, new_keys = await updater.update_key(thing)
2024-07-08 18:26:27                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/openlibrary/openlibrary/solr/updater/author.py", line 16, in update_key
2024-07-08 18:26:27     response = await client.get(
2024-07-08 18:26:27                ^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpx/_client.py", line 1757, in get
2024-07-08 18:26:27     return await self.request(
2024-07-08 18:26:27            ^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpx/_client.py", line 1530, in request
2024-07-08 18:26:27     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
2024-07-08 18:26:27            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpx/_client.py", line 1617, in send
2024-07-08 18:26:27     response = await self._send_handling_auth(
2024-07-08 18:26:27                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
2024-07-08 18:26:27     response = await self._send_handling_redirects(
2024-07-08 18:26:27                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
2024-07-08 18:26:27     response = await self._send_single_request(request)
2024-07-08 18:26:27                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpx/_client.py", line 1719, in _send_single_request
2024-07-08 18:26:27     response = await transport.handle_async_request(request)
2024-07-08 18:26:27                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
2024-07-08 18:26:27     with map_httpcore_exceptions():
2024-07-08 18:26:27   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
2024-07-08 18:26:27     self.gen.throw(value)
2024-07-08 18:26:27   File "/home/openlibrary/.local/lib/python3.12/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
2024-07-08 18:26:27     raise mapped_exc(message) from exc
2024-07-08 18:26:27 httpx.ConnectError: [Errno -2] Name or service not known
2024-07-08 18:26:27 2024-07-08 22:26:27 [openlibrary.solr-updater] [INFO] updated 1 documents
2024-07-08 18:26:27 2024-07-08 22:26:27 [openlibrary.solr-updater] [INFO] saving offset 2024-07-08:1455```
#### Relevant URL(s)


### Reproducing the bug

1. Go to http://localhost:8080/admin/solr
2. Attempt to update a Solr key through this endpoint.

* Expected behavior: The Solr records of that key should be updated.
* Actual behavior: The search request errors out. 


### Context

- Browser (Chrome, Safari, Firefox, etc): Chrome
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): dev


### Notes from this Issue's Lead

#### Proposal & constraints
<!-- What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere? -->

#### Related files
<!-- Files related to this issue; this is super useful for new contributors who might want to help! If you're not sure, leave this blank; a maintainer will add them. -->

#### Stakeholders
<!-- @ tag stakeholders of this bug -->
<hr>

#### Instructions for Contributors
<!-- Please leave the following reminder section as is to help new contributors and add instructions where necessary -->

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by benbdeitch** [comment]
This issue can be closed; it was a problem with my docker installation, and has since been fixed.

**Comment by benbdeitch** [comment]
This issue  was a problem with my docker installation, and was fixed by resetting my environment.
