### ISSUE TITLE
Batch import endpoint errors if patron is not logged in

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9980]
### Problem

If one uses the batch import endpoint at http://localhost:8080/import/batch/new without being logged in, it causes an error. This page should _only_ show for logged in patrons, and should likely invite people to log in if not already logged in.

### Reproducing the bug

1. Go to http://localhost:8080/import/batch/new while NOT logged in.
2. Enter one or more JSNOL import records. E.g. `{"title": "Gustave Courbet THE GREAT", "subtitle": "with a biographical and critical study", "authors": [{"name": "Léonce Bénédite"}], "publishers": ["J.B. Lippincott company", "W. Heinemann"], "publish_date": "1916", "contributors": [{"name": "Blobby McTranslator", "role": "Translator"}], "source_records": ["marc:marc_binghamton_univ/bgm_openlib_final_0-5.mrc:115814933:819"]}`

* Expected behavior: The record is added to the import queue as normal.
* Actual behavior: there is an error as follows:
![image](https://github.com/user-attachments/assets/e9023ec6-4e3b-4a5e-9557-3ce542e015e2)

The console says:
```
db-1            | ERROR:  column "submitter" of relation "import_item" does not exist at character 57
db-1            | STATEMENT:  INSERT INTO import_item (batch_id, data, ia_id, status, submitter) VALUES (1, '{"authors": [{"name": "L\u00e9once B\u00e9n\u00e9dite"}], "contributors": [{"name": "Blobby McTranslator", "role": "Translator"}], "publish_date": "1916", "publishers": ["J.B. Lippincott company", "W. Heinemann"], "source_records": ["marc:marc_binghamton_univ/bgm_openlib_final_0-5.mrc:115814933:819"], "subtitle": "with a biographical and critical study", "title": "Gustave Courbet THE GREAT"}', 'marc:marc_binghamton_univ/bgm_openlib_final_0-5.mrc:115814933:819', 'pending', 'openlibrary'); SELECT currval('import_item_id_seq')
web-1           | ERR: INSERT INTO import_item (batch_id, data, ia_id, status, submitter) VALUES (1, '{"authors": [{"name": "L\\u00e9once B\\u00e9n\\u00e9dite"}], "contributors": [{"name": "Blobby McTranslator", "role": "Translator"}], "publish_date": "1916", "publishers": ["J.B. Lippincott company", "W. Heinemann"], "source_records": ["marc:marc_binghamton_univ/bgm_openlib_final_0-5.mrc:115814933:819"], "subtitle": "with a biographical and critical study", "title": "Gustave Courbet THE GREAT"}', 'marc:marc_binghamton_univ/bgm_openlib_final_0-5.mrc:115814933:819', 'pending', 'openlibrary'); SELECT currval('import_item_id_seq')
web-1           | Traceback (most recent call last):
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 276, in process
web-1           |     return self.handle()
web-1           |            ^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 267, in handle
web-1           |     return self._delegate(fn, self.fvars, args)
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 509, in _delegate
web-1           |     return handle_class(cls)
web-1           |            ^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 487, in handle_class
web-1           |     return tocall(*args)
web-1           |            ^^^^^^^^^^^^^
web-1           |   File "/openlibrary/infogami/utils/app.py", line 197, in <lambda>
web-1           |     HEAD = GET = POST = PUT = DELETE = lambda self: delegate()
web-1           |                                                     ^^^^^^^^^^
web-1           |   File "/openlibrary/infogami/utils/app.py", line 217, in delegate
web-1           |     return getattr(cls(), method)(*args)
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/openlibrary/openlibrary/plugins/openlibrary/code.py", line 519, in POST
web-1           |     batch_result = batch_import(
web-1           |                    ^^^^^^^^^^^^^
web-1           |   File "/openlibrary/openlibrary/core/batch_imports.py", line 141, in batch_import
web-1           |     batch.add_items(batch_data)
web-1           |   File "/openlibrary/openlibrary/core/imports.py", line 128, in add_items
web-1           |     db.get_db().multiple_insert("import_item", items)
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/db.py", line 1073, in multiple_insert
web-1           |     self._db_execute(db_cursor, sql_query)
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/db.py", line 745, in _db_execute
web-1           |     out = cur.execute(query, params)
web-1           |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           | psycopg2.errors.UndefinedColumn: column "submitter" of relation "import_item" does not exist
web-1           | LINE 1: ... INTO import_item (batch_id, data, ia_id, status, submitter)...
web-1           |                                                              ^
```

The key problem being there is no submitter if not logged in. We don't want a default submitter, though. We want people to be logged in (and thus there will be a submitter) for this page to display.

#### Requirements Checklist
* [ ] Make http://localhost:8080/import/batch/new display ONLY for logged in patrons.

#### Related files

* See the PRs linked below.

#### Stakeholders

*
<hr>

#### Instructions for Contributors

See the following PRs for more context about this endpoint and how it is used, to the extent it is helpful:
- https://github.com/internetarchive/openlibrary/pull/8122
- https://github.com/internetarchive/openlibrary/pull/9862
- https://github.com/internetarchive/openlibrary/pull/9939 for more information.

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by scottbarnes** [comment]
Or I've just blown away my database at some point and no longer have the `submitter` column, as I'd have noticed if I didn't merely assume the error text said what I had expected it to say. I think it is time to sleep.
